# Generated by Django 5.2.7 on 2025-12-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('employes', '0004_accidenttravail_avenantcontrat_equipementprotection_and_more'),
        ('recrutement', '0002_candidature_employe_cree_offreemploi_entreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_canal', models.CharField(choices=[('site_web', 'Site web entreprise'), ('linkedin', 'LinkedIn'), ('jobboard', "Site d'emploi"), ('presse', 'Presse'), ('agence', 'Agence de recrutement'), ('cooptation', 'Cooptation'), ('ecole', 'École/Université'), ('autre', 'Autre')], max_length=30)),
                ('nom_canal', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_publication', models.DateField()),
                ('date_retrait', models.DateField(blank=True, null=True)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nb_candidatures_recues', models.IntegerField(default=0)),
                ('observations', models.TextField(blank=True, null=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaux_diffusion', to='recrutement.offreemploi')),
            ],
            options={
                'verbose_name': 'Canal de diffusion',
                'verbose_name_plural': 'Canaux de diffusion',
                'db_table': 'canaux_diffusion',
            },
        ),
        migrations.CreateModel(
            name='DecisionEmbauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('embauche', 'Embauche validée'), ('refus', 'Refus'), ('attente', 'En attente'), ('reserve', 'Mise en réserve')], max_length=20)),
                ('date_decision', models.DateField()),
                ('type_contrat', models.CharField(blank=True, max_length=20, null=True)),
                ('date_embauche_prevue', models.DateField(blank=True, null=True)),
                ('salaire_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('casier_judiciaire', models.BooleanField(default=False, help_text='Casier judiciaire fourni')),
                ('certificat_medical', models.BooleanField(default=False, help_text='Certificat médical fourni')),
                ('diplomes_verifies', models.BooleanField(default=False, help_text='Diplômes vérifiés')),
                ('references_verifiees', models.BooleanField(default=False, help_text='Références vérifiées')),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_embauche', to='recrutement.candidature')),
                ('poste_propose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.poste')),
                ('service_affectation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embauches_validees', to='employes.employe')),
            ],
            options={
                'verbose_name': "Décision d'embauche",
                'verbose_name_plural': "Décisions d'embauche",
                'db_table': 'decisions_embauche',
                'ordering': ['-date_decision'],
            },
        ),
        migrations.CreateModel(
            name='TestRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_test', models.CharField(choices=[('technique', 'Test technique'), ('psychotechnique', 'Test psychotechnique'), ('personnalite', 'Test de personnalité'), ('langue', 'Test de langue'), ('pratique', 'Test pratique'), ('cas_etude', 'Étude de cas')], max_length=30)),
                ('intitule', models.CharField(max_length=200)),
                ('date_test', models.DateTimeField()),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('score_obtenu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_max', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('seuil_reussite', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('resultat', models.CharField(choices=[('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('fichier_test', models.FileField(blank=True, null=True, upload_to='recrutement/tests/')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='recrutement.candidature')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
            ],
            options={
                'verbose_name': 'Test de recrutement',
                'verbose_name_plural': 'Tests de recrutement',
                'db_table': 'tests_recrutement',
                'ordering': ['-date_test'],
            },
        ),
    ]
