# Generated by Django 5.2.7 on 2025-12-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_canaldiffusion_decisionembauche_testrecrutement'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de présentation de l'offre", null=True, upload_to='offres_emploi/'),
        ),
    ]
