# Generated by Django 5.2.7 on 2025-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_offreemploi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='autres_documents',
            field=models.FileField(blank=True, help_text='Autres documents (diplômes, certificats, etc.)', null=True, upload_to='candidatures/autres/'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv_fichier',
            field=models.FileField(blank=True, help_text='CV au format PDF', null=True, upload_to='candidatures/cv/'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, help_text='Lettre de motivation', null=True, upload_to='candidatures/lettres/'),
        ),
    ]
