# Generated by Django 5.2.7 on 2026-01-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_candidature_autres_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='document_pdf',
            field=models.FileField(blank=True, help_text='Document PDF (fiche de poste, description...)', null=True, upload_to='offres_emploi/documents/'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='reference_poste',
            field=models.CharField(blank=True, help_text='Référence interne du poste', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='secteur_activite',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Banque/Finance', 'Banque / Finance'), ('BTP', 'BTP / Construction'), ('Commerce', 'Commerce / Distribution'), ('Education', 'Éducation / Formation'), ('Energie', 'Énergie / Environnement'), ('Industrie', 'Industrie / Production'), ('Informatique', 'Informatique / Technologies'), ('Mines', 'Mines / Ressources naturelles'), ('Sante', 'Santé / Médical'), ('Services', 'Services aux entreprises'), ('Telecom', 'Télécommunications'), ('Transport', 'Transport / Logistique'), ('Tourisme', 'Tourisme / Hôtellerie'), ('Autre', 'Autre')], max_length=50, null=True),
        ),
    ]
