# Generated by Django 5.2.7 on 2026-01-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_add_reference_secteur_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='poste_texte',
            field=models.CharField(blank=True, help_text='Poste saisi manuellement', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='responsable_texte',
            field=models.CharField(blank=True, help_text='Responsable saisi manuellement', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='service_texte',
            field=models.CharField(blank=True, help_text='Service saisi manuellement', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
