# Generated by Django 5.2.7 on 2026-01-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0007_add_texte_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionembauche',
            name='date_debut_integration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionembauche',
            name='date_envoi_offre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionembauche',
            name='date_reponse_candidat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionembauche',
            name='statut_integration',
            field=models.CharField(choices=[('offre_envoyee', 'Offre envoyée'), ('offre_acceptee', 'Offre acceptée'), ('offre_refusee', 'Offre refusée'), ('documents_attente', 'Documents en attente'), ('integration_cours', 'Intégration en cours'), ('integration_terminee', 'Intégration terminée')], default='offre_envoyee', max_length=30),
        ),
    ]
