# Generated by Django 5.2.7 on 2026-01-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0015_add_conjoint_et_docs'),
        ('recrutement', '0008_decisionembauche_date_debut_integration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessusIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_prevue', models.DateField()),
                ('date_debut_effective', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_effective', models.DateField(blank=True, null=True)),
                ('etape_actuelle', models.CharField(choices=[('documents_pre_embauche', 'Documents pré-embauche'), ('signature_contrat', 'Signature contrat'), ('accueil_premier_jour', 'Accueil premier jour'), ('formation_securite', 'Formation sécurité'), ('presentation_equipe', 'Présentation équipe'), ('formation_poste', 'Formation au poste'), ('evaluation_periode_essai', "Évaluation période d'essai"), ('integration_terminee', 'Intégration terminée')], default='documents_pre_embauche', max_length=30)),
                ('pourcentage_completion', models.IntegerField(default=0)),
                ('note_integration', models.IntegerField(blank=True, help_text='Note sur 10', null=True)),
                ('commentaires_integration', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('decision_embauche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processus_integration', to='recrutement.decisionembauche')),
                ('employe_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processus_integration', to='employes.employe')),
                ('responsable_integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_gerees', to='employes.employe')),
                ('tuteur_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorats', to='employes.employe')),
            ],
            options={
                'verbose_name': "Processus d'intégration",
                'verbose_name_plural': "Processus d'intégration",
                'db_table': 'processus_integration',
            },
        ),
        migrations.CreateModel(
            name='EtapeIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etape', models.CharField(choices=[('documents_pre_embauche', 'Documents pré-embauche'), ('signature_contrat', 'Signature contrat'), ('accueil_premier_jour', 'Accueil premier jour'), ('formation_securite', 'Formation sécurité'), ('presentation_equipe', 'Présentation équipe'), ('formation_poste', 'Formation au poste'), ('evaluation_periode_essai', "Évaluation période d'essai"), ('integration_terminee', 'Intégration terminée')], max_length=30)),
                ('description', models.TextField()),
                ('date_prevue', models.DateField()),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('duree_estimee_heures', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('bloquee', 'Bloquée')], default='a_faire', max_length=20)),
                ('documents_requis', models.TextField(blank=True, null=True)),
                ('documents_fournis', models.BooleanField(default=False)),
                ('validation_requise', models.BooleanField(default=False)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=1)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_validees', to='employes.employe')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_integration', to='recrutement.processusintegration')),
            ],
            options={
                'verbose_name': "Étape d'intégration",
                'verbose_name_plural': "Étapes d'intégration",
                'db_table': 'etapes_integration',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AlerteIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('retard_etape', 'Retard sur étape'), ('document_manquant', 'Document manquant'), ('validation_requise', 'Validation requise'), ('fin_periode_essai', "Fin période d'essai")], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('traitee', models.BooleanField(default=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='recrutement.processusintegration')),
            ],
            options={
                'verbose_name': 'Alerte intégration',
                'verbose_name_plural': 'Alertes intégration',
                'db_table': 'alertes_integration',
                'ordering': ['date_echeance'],
            },
        ),
    ]
