# Generated by Django 5.2.6 on 2026-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entreprise_modules_quotas_plan'),
        ('employes', '0017_ajout_vehicule_assigne'),
        ('recrutement', '0009_processusintegration_etapeintegration_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['offre', 'statut_candidature'], name='idx_cand_offre_statut'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['date_candidature'], name='idx_cand_date'),
        ),
        migrations.AddIndex(
            model_name='entretienrecrutement',
            index=models.Index(fields=['candidature', 'date_entretien'], name='idx_entretien_cand_date'),
        ),
        migrations.AddIndex(
            model_name='entretienrecrutement',
            index=models.Index(fields=['date_entretien'], name='idx_entretien_date'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['entreprise', 'statut_offre'], name='idx_offre_ent_statut'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['date_publication'], name='idx_offre_date_pub'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=models.Index(fields=['date_limite_candidature'], name='idx_offre_date_limite'),
        ),
    ]
