# Generated by Django 4.2.7 on 2026-04-25 17:36

import core.validators
from django.db import migrations, models
import recrutement.models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutement", "0011_offreemploi_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="autres_documents",
            field=models.FileField(
                blank=True,
                help_text="Autres documents (PDF, Word, JPEG, PNG)",
                null=True,
                upload_to=recrutement.models.chemin_autre_doc,
                validators=[core.validators.valider_image_document],
            ),
        ),
        migrations.AlterField(
            model_name="candidature",
            name="cv_fichier",
            field=models.FileField(
                blank=True,
                help_text="CV au format PDF ou Word, max 5 Mo",
                null=True,
                upload_to=recrutement.models.chemin_cv,
                validators=[core.validators.valider_cv],
            ),
        ),
        migrations.AlterField(
            model_name="candidature",
            name="lettre_motivation",
            field=models.FileField(
                blank=True,
                help_text="Lettre de motivation (PDF ou Word)",
                null=True,
                upload_to=recrutement.models.chemin_lettre,
                validators=[core.validators.valider_cv],
            ),
        ),
        migrations.AlterField(
            model_name="offreemploi",
            name="document_pdf",
            field=models.FileField(
                blank=True,
                help_text="Document PDF (fiche de poste, description...)",
                null=True,
                upload_to="offres_emploi/documents/",
                validators=[core.validators.valider_cv],
            ),
        ),
        migrations.AlterField(
            model_name="offreemploi",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image de présentation de l'offre (JPEG/PNG)",
                null=True,
                upload_to="offres_emploi/",
                validators=[core.validators.valider_image],
            ),
        ),
    ]
