# Generated by Django 4.2.7 on 2026-04-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recrutement", "0012_alter_candidature_autres_documents_and_more"),
        ("recrutement", "0012_candidature_taille_validators"),
    ]

    operations = []
