# Generated by Django 5.2.11 on 2026-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_plans_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='planabonnement',
            name='badge',
            field=models.CharField(blank=True, help_text='Ex: Populaire, Recommandé', max_length=30),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='couleur',
            field=models.CharField(default='#0d6efd', help_text='Couleur principale hex', max_length=7),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='declarations_fiscales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='export_comptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='formation_incluse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='icone',
            field=models.CharField(default='bi-box', help_text='Classe Bootstrap Icons', max_length=50),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='module_comptabilite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='module_portail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='multi_entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='personnalisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='prix_installation',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Frais d'installation one-shot en GNF", max_digits=12),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='sous_titre',
            field=models.CharField(blank=True, help_text='Ex: Idéal pour les petites entreprises', max_length=100),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='support_telephonique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('abonnement', 'Abonnement'), ('renouvellement', 'Renouvellement'), ('upgrade', 'Mise à niveau'), ('installation', 'Installation & Configuration')], default='abonnement', max_length=20),
        ),
    ]
