# Generated by Django 4.2.29 on 2026-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_mise_a_jour_offres_commerciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='passerelle',
            field=models.CharField(blank=True, choices=[('cinetpay', 'CinetPay'), ('paycard', 'Paycard')], default='paycard', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('visa', 'Carte Visa'), ('mastercard', 'Carte Mastercard'), ('paydunya', 'PayDunya'), ('paycard', 'Paycard')], max_length=20, null=True),
        ),
    ]
