# Generated by Django 5.2.7 on 2025-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entreprise_utilisateur_est_admin_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societes', to='core.entreprise'),
        ),
    ]
