# Generated by Django 5.2.7 on 2025-12-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devise_configurationcnss_expatrie_permisvisa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('affichage_horaires', 'Horaires de travail affichés'), ('affichage_reglement', 'Règlement intérieur affiché'), ('affichage_securite', 'Consignes de sécurité affichées'), ('affichage_inspection', 'Coordonnées inspection du travail'), ('affichage_medecine', 'Coordonnées médecine du travail'), ('securite_extincteurs', 'Extincteurs vérifiés'), ('securite_trousse', 'Trousse de premiers secours'), ('securite_equipements', 'Équipements de protection fournis')], max_length=50)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('validateur', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_conformite', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Paramètre de conformité',
                'verbose_name_plural': 'Paramètres de conformité',
                'db_table': 'parametres_conformite',
                'unique_together': {('entreprise', 'code')},
            },
        ),
    ]
