# Generated by Django 5.2.7 on 2026-01-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_parametre_conformite'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
    ]
