# Generated by Django 5.2.7 on 2026-01-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_secteur_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePartenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Guinée', max_length=50, verbose_name='Pays')),
                ('nom_contact', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('fonction_contact', models.CharField(max_length=100, verbose_name='Fonction')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('type_partenariat', models.CharField(choices=[('revendeur', 'Revendeur'), ('integrateur', 'Intégrateur'), ('consultant', 'Consultant'), ('formation', 'Centre de formation'), ('autre', 'Autre')], max_length=20, verbose_name='Type de partenariat')),
                ('description_activite', models.TextField(verbose_name="Description de l'activité")),
                ('motivation', models.TextField(verbose_name='Motivation pour le partenariat')),
                ('document_cgi', models.FileField(blank=True, null=True, upload_to='partenariats/documents/', verbose_name='Document CGI')),
                ('autre_document', models.FileField(blank=True, null=True, upload_to='partenariats/documents/', verbose_name='Autre document')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='nouveau', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, null=True, verbose_name='Notes administrateur')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'db_table': 'demandes_partenariat',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
