# Generated by Django 5.2.7 on 2026-01-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_demande_partenariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='type_module',
            field=models.CharField(choices=[('rh', 'Ressources Humaines'), ('compta', 'Comptabilité'), ('both', 'RH + Comptabilité')], default='rh', max_length=10, verbose_name='Type de compte'),
        ),
    ]
