# Generated by Django 5.2.7 on 2026-01-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entreprise_type_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='expatrie',
            name='contact_urgence_pays',
            field=models.CharField(blank=True, help_text="Contact d'urgence au pays d'origine", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expatrie',
            name='date_arrivee',
            field=models.DateField(blank=True, help_text="Date d'arrivée en Guinée", null=True),
        ),
        migrations.AddField(
            model_name='expatrie',
            name='duree_prevue_mois',
            field=models.IntegerField(blank=True, help_text='Durée prévue en mois', null=True),
        ),
        migrations.AddField(
            model_name='expatrie',
            name='motif_expatriation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expatrie',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expatrie',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='expatrie',
            name='devise_salaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expatries', to='core.devise'),
        ),
    ]
