# Generated by Django 5.2.11 on 2026-02-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_expatrie_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_licence', models.CharField(editable=False, max_length=50, unique=True)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('email_contact', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('type_licence', models.CharField(choices=[('trial', 'Essai (30 jours)'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('perpetuel', 'Perpétuel')], default='trial', max_length=20)),
                ('plan', models.CharField(choices=[('starter', 'Starter - 10 employés max'), ('pro', 'Professionnel - 50 employés max'), ('enterprise', 'Entreprise - Illimité')], default='starter', max_length=20)),
                ('max_employes', models.IntegerField(default=10)),
                ('max_utilisateurs', models.IntegerField(default=2)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=False)),
                ('est_bloquee', models.BooleanField(default=False)),
                ('raison_blocage', models.TextField(blank=True)),
                ('machine_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
            },
        ),
        migrations.CreateModel(
            name='LicenceLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_licence', models.CharField(max_length=50)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=20)),
                ('max_employes', models.IntegerField(default=10)),
                ('max_utilisateurs', models.IntegerField(default=2)),
                ('date_activation', models.DateTimeField()),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('machine_id', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Licence locale',
                'verbose_name_plural': 'Licences locales',
            },
        ),
    ]
