# Generated by Django 5.2.11 on 2026-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_licence_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='acces_declarations_fiscales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='acces_export_comptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='max_employes',
            field=models.IntegerField(default=30, help_text="Nombre maximum d'employés"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='module_comptabilite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='module_conges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='module_formation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='module_paie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='module_portail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='module_recrutement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='plan_abonnement',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('basique', 'Basique'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium'), ('entreprise', 'Entreprise')], default='gratuit', max_length=50),
        ),
    ]
