# Generated by Django 4.2.29 on 2026-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entreprise_modules_quotas_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='banque_cle_rib',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Clé RIB'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='banque_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code banque'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='banque_compte',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='banque_guichet',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code guichet'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='banque_iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='banque_nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nifp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF-p (eTax DGI)'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telepaiement_autorise',
            field=models.BooleanField(default=False, verbose_name='Télépaiement DGI autorisé'),
        ),
    ]
