# Generated by Django 4.2.29 on 2026-04-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_poste_par_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeCodeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('code_saisi', models.CharField(max_length=20)),
                ('succes', models.BooleanField(default=False)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': "Tentative code d'accès",
                'verbose_name_plural': "Tentatives code d'accès",
                'db_table': 'tentatives_code_acces',
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.AddIndex(
            model_name='tentativecodeacces',
            index=models.Index(fields=['adresse_ip', 'date_tentative'], name='tentatives__adresse_4d64a9_idx'),
        ),
    ]
