# Generated by Django 5.2.1 on 2026-04-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tentative_code_acces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Licence',
        ),
        migrations.DeleteModel(
            name='LicenceLocale',
        ),
    ]
