# Generated by Django 4.2.29 on 2026-07-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_licence_licencelocale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('accorde_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_accordes', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_utilisateurs', to='core.entreprise')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_entreprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès entreprise (multi-sociétés)',
                'verbose_name_plural': 'Accès entreprises (multi-sociétés)',
                'db_table': 'acces_entreprises',
                'unique_together': {('utilisateur', 'entreprise')},
            },
        ),
    ]
