# Generated by Django 4.2.29 on 2026-07-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_accesentreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesentreprise',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accesentreprise',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début de validité (vide = immédiat)'),
        ),
        migrations.AddField(
            model_name='accesentreprise',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de validité (vide = illimité)'),
        ),
        migrations.AddField(
            model_name='accesentreprise',
            name='role',
            field=models.CharField(choices=[('comptable', 'Comptable (saisie)'), ('chef_comptable', 'Chef comptable (validation comptable)'), ('daf', 'DAF (validation financière)'), ('dg', 'Directeur général (validation exceptionnelle)'), ('auditeur', 'Auditeur (lecture seule)'), ('administrateur', 'Administrateur (paramétrage)')], default='comptable', max_length=20, verbose_name='Rôle dans cette entreprise'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.entreprise'),
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('comptable', 'Comptable (saisie)'), ('chef_comptable', 'Chef comptable (validation comptable)'), ('daf', 'DAF (validation financière)'), ('dg', 'Directeur général (validation exceptionnelle)'), ('auditeur', 'Auditeur (lecture seule)'), ('administrateur', 'Administrateur (paramétrage)')], max_length=20)),
                ('permission', models.CharField(max_length=60, verbose_name='Code permission')),
            ],
            options={
                'verbose_name': 'Permission de rôle',
                'verbose_name_plural': 'Permissions des rôles',
                'db_table': 'permissions_roles',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(verbose_name='Fin')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif (congé, mission…)')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('delegant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_accordees', to=settings.AUTH_USER_MODEL)),
                ('delegataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_obtenues', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'db_table': 'delegations',
            },
        ),
    ]
