# Generated by Django 5.2.7 on 2025-10-21 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriquePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_rubrique', models.CharField(max_length=20, unique=True)),
                ('libelle_rubrique', models.CharField(max_length=200)),
                ('type_rubrique', models.CharField(choices=[('gain', 'Gain'), ('retenue', 'Retenue'), ('cotisation', 'Cotisation'), ('information', 'Information')], max_length=20)),
                ('formule_calcul', models.TextField(blank=True, null=True)),
                ('taux_rubrique', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('soumis_cnss', models.BooleanField(default=False)),
                ('soumis_irg', models.BooleanField(default=False)),
                ('ordre_calcul', models.IntegerField(default=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rubrique de paie',
                'verbose_name_plural': 'Rubriques de paie',
                'db_table': 'rubriques_paie',
                'ordering': ['ordre_calcul'],
            },
        ),
        migrations.CreateModel(
            name='PeriodePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut_periode', models.CharField(choices=[('ouverte', 'Ouverte'), ('calculee', 'Calculée'), ('validee', 'Validée'), ('cloturee', 'Clôturée'), ('payee', 'Payée')], default='ouverte', max_length=20)),
                ('nombre_jours_travailles', models.IntegerField(default=22)),
                ('nombre_heures_mois', models.DecimalField(decimal_places=2, default=173.33, max_digits=6)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('utilisateur_cloture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_cloturees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Période de paie',
                'verbose_name_plural': 'Périodes de paie',
                'db_table': 'periodes_paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bulletin', models.CharField(max_length=50, unique=True)),
                ('mois_paie', models.IntegerField()),
                ('annee_paie', models.IntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cnss_employe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('irg', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cnss_employeur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut_bulletin', models.CharField(choices=[('brouillon', 'Brouillon'), ('calcule', 'Calculé'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('date_calcul', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='employes.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='paie.periodepaie')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'db_table': 'bulletins_paie',
                'ordering': ['-annee_paie', '-mois_paie'],
                'unique_together': {('employe', 'periode')},
            },
        ),
    ]
