# Generated by Django 5.2.7 on 2025-10-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_constante_trancheirg_variable_parametrepaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriquepaie',
            name='affichage_bulletin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubriquepaie',
            name='ordre_affichage',
            field=models.IntegerField(default=100),
        ),
    ]
