# Generated by Django 5.2.7 on 2025-10-21 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        ('paie', '0003_rubriquepaie_affichage_bulletin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe', max_digits=15, null=True)),
                ('taux', models.DecimalField(blank=True, decimal_places=4, help_text='Taux en %', max_digits=8, null=True)),
                ('base_calcul', models.CharField(blank=True, help_text='Ex: SALAIRE_BASE, BRUT, etc.', max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('recurrent', models.BooleanField(default=True, help_text='Appliqué chaque mois')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_salaire', to='employes.employe')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_employes', to='paie.rubriquepaie')),
            ],
            options={
                'verbose_name': 'Élément de salaire',
                'verbose_name_plural': 'Éléments de salaire',
                'db_table': 'elements_salaire',
                'ordering': ['employe', 'rubrique__ordre_calcul'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('validation', 'Validation'), ('cloture', 'Clôture'), ('recalcul', 'Recalcul')], max_length=20)),
                ('description', models.TextField()),
                ('valeurs_avant', models.JSONField(blank=True, null=True)),
                ('valeurs_apres', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='paie.bulletinpaie')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_paie', to='employes.employe')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='paie.periodepaie')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de paie',
                'verbose_name_plural': 'Historiques de paie',
                'db_table': 'historique_paie',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0, help_text='Base de calcul', max_digits=15)),
                ('taux', models.DecimalField(blank=True, decimal_places=4, help_text='Taux appliqué', max_digits=8, null=True)),
                ('nombre', models.DecimalField(decimal_places=2, default=1, help_text='Quantité (heures, jours, etc.)', max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Montant calculé', max_digits=15)),
                ('ordre', models.IntegerField(default=100)),
                ('libelle_personnalise', models.CharField(blank=True, help_text='Libellé spécifique pour ce bulletin', max_length=200)),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.bulletinpaie')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.rubriquepaie')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'verbose_name_plural': 'Lignes de bulletin',
                'db_table': 'lignes_bulletin',
                'ordering': ['bulletin', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='CumulPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('cumul_brut', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumul_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumul_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumul_cnss_employe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumul_cnss_employeur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumul_irg', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumuls_rubriques', models.JSONField(blank=True, default=dict, help_text='Cumuls détaillés par rubrique')),
                ('nombre_bulletins', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumuls_paie', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Cumul de paie',
                'verbose_name_plural': 'Cumuls de paie',
                'db_table': 'cumuls_paie',
                'ordering': ['-annee', 'employe'],
                'unique_together': {('employe', 'annee')},
            },
        ),
    ]
