# Generated by Django 5.2.7 on 2025-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('paie', '0004_elementsalaire_historiquepaie_lignebulletin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodepaie',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='periodepaie',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodes_paie', to='core.entreprise'),
        ),
        migrations.AlterUniqueTogether(
            name='periodepaie',
            unique_together={('entreprise', 'annee', 'mois')},
        ),
    ]
