# Generated by Django 5.2.7 on 2025-10-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='responsable_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to='employes.employe'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_services', to='core.service'),
        ),
        migrations.AddField(
            model_name='poste',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='core.service'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='core.societe'),
        ),
        migrations.AlterUniqueTogether(
            name='droitacces',
            unique_together={('profil', 'module')},
        ),
    ]
