# Generated by Django 5.2.7 on 2025-10-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='num_cnss_employeur',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° CNSS Employeur'),
        ),
    ]
