# Generated by Django 5.2.7 on 2025-10-26 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_societe_nif_alter_societe_num_cnss_employeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nif', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NIF')),
                ('num_cnss', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° CNSS')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default='Guinée', max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, help_text="Date d'expiration de l'abonnement", null=True)),
                ('actif', models.BooleanField(default=True)),
                ('plan_abonnement', models.CharField(choices=[('gratuit', 'Gratuit'), ('basique', 'Basique'), ('premium', 'Premium'), ('entreprise', 'Entreprise')], default='gratuit', max_length=50)),
                ('max_utilisateurs', models.IntegerField(default=5, help_text="Nombre maximum d'utilisateurs")),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'entreprises',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_admin_entreprise',
            field=models.BooleanField(default=False, help_text="Administrateur de l'entreprise"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_reauth',
            field=models.DateTimeField(blank=True, help_text='Dernière réauthentification', null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='require_reauth',
            field=models.BooleanField(default=False, help_text='Nécessite une réauthentification pour accéder aux menus'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='core.entreprise'),
        ),
    ]
