# Generated by Django 5.2.7 on 2025-10-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_candidature', models.CharField(max_length=50, unique=True)),
                ('civilite', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('formation_niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_annees', models.IntegerField(blank=True, null=True)),
                ('date_candidature', models.DateField(auto_now_add=True)),
                ('cv_fichier', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidatures/lettres/')),
                ('statut_candidature', models.CharField(choices=[('recue', 'Reçue'), ('preselectionne', 'Présélectionnée'), ('entretien', 'Entretien'), ('retenue', 'Retenue'), ('rejetee', 'Rejetée')], default='recue', max_length=20)),
                ('score_evaluation', models.IntegerField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('date_entretien', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'db_table': 'candidatures',
                'ordering': ['-date_candidature'],
            },
        ),
        migrations.CreateModel(
            name='EntretienRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('telephonique', 'Téléphonique'), ('presentiel', 'Présentiel'), ('visio', 'Visioconférence'), ('technique', 'Technique'), ('rh', 'RH')], max_length=50)),
                ('date_entretien', models.DateTimeField()),
                ('lieu_entretien', models.CharField(blank=True, max_length=200, null=True)),
                ('intervieweurs', models.TextField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('evaluation_technique', models.IntegerField(blank=True, null=True)),
                ('evaluation_comportementale', models.IntegerField(blank=True, null=True)),
                ('evaluation_motivation', models.IntegerField(blank=True, null=True)),
                ('note_globale', models.IntegerField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('defavorable', 'Défavorable'), ('a_revoir', 'À revoir')], max_length=50, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='recrutement.candidature')),
            ],
            options={
                'verbose_name': 'Entretien de recrutement',
                'verbose_name_plural': 'Entretiens de recrutement',
                'db_table': 'entretiens_recrutement',
                'ordering': ['-date_entretien'],
            },
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_offre', models.CharField(max_length=50, unique=True)),
                ('intitule_poste', models.CharField(max_length=200)),
                ('type_contrat', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_postes', models.IntegerField(default=1)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_limite_candidature', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('description_poste', models.TextField(blank=True, null=True)),
                ('profil_recherche', models.TextField(blank=True, null=True)),
                ('competences_requises', models.TextField(blank=True, null=True)),
                ('experience_requise', models.IntegerField(blank=True, null=True)),
                ('formation_requise', models.CharField(blank=True, max_length=200, null=True)),
                ('salaire_propose_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salaire_propose_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avantages', models.TextField(blank=True, null=True)),
                ('statut_offre', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée'), ('pourvue', 'Pourvue'), ('annulee', 'Annulée')], default='ouverte', max_length=20)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.poste')),
                ('responsable_recrutement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'db_table': 'offres_emploi',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutement.offreemploi'),
        ),
    ]
