# Generated by Django 5.2.7 on 2025-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('employes', '0003_employe_entreprise_and_more'),
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='employe_cree',
            field=models.OneToOneField(blank=True, help_text="Employé créé suite à l'embauche", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature_origine', to='employes.employe'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_emploi', to='core.entreprise'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut_candidature',
            field=models.CharField(choices=[('recue', 'Reçue'), ('preselectionne', 'Présélectionnée'), ('entretien', 'Entretien'), ('retenue', 'Retenue'), ('rejetee', 'Rejetée'), ('embauche', 'Embauché')], default='recue', max_length=20),
        ),
    ]
