# Generated by Django 5.2.7 on 2025-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('employes', '0002_documentemploye'),
        ('formation', '0003_catalogueformation_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes_entreprise', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='formationemploye',
            name='inscription_formation',
            field=models.OneToOneField(blank=True, help_text="Lien vers l'inscription dans le module formation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_employe', to='formation.inscriptionformation'),
        ),
    ]
