# Generated by Django 5.2.7 on 2025-12-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0005_add_devise_paie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('stage', 'Stage'), ('temporaire', 'Temporaire')], max_length=20, null=True),
        ),
    ]
