# Generated by Django 5.2.7 on 2025-12-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0006_rendre_champs_optionnels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratemploye',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('stage', 'Stage'), ('apprentissage', "Contrat d'Apprentissage"), ('temporaire', 'Temporaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('stage', 'Stage'), ('apprentissage', "Contrat d'Apprentissage"), ('temporaire', 'Temporaire')], max_length=20, null=True),
        ),
    ]
