# Generated by Django 5.2.7 on 2025-12-28 11:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0008_evaluation_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeIndemnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('conakry', 'Conakry'), ('interieur', 'Intérieur du pays'), ('afrique', 'Afrique'), ('international', 'International')], max_length=30)),
                ('categorie_employe', models.CharField(blank=True, choices=[('direction', 'Direction'), ('cadre_superieur', 'Cadre supérieur'), ('cadre', 'Cadre'), ('agent_maitrise', 'Agent de maîtrise'), ('employe', 'Employé')], help_text='Laisser vide pour tous', max_length=50)),
                ('indemnite_journaliere', models.DecimalField(decimal_places=2, help_text='Per diem en GNF', max_digits=15)),
                ('plafond_hebergement', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond hébergement/nuit en GNF', max_digits=15, null=True)),
                ('plafond_restauration', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond restauration/jour en GNF', max_digits=15, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Barème indemnité',
                'verbose_name_plural': 'Barèmes indemnités',
                'db_table': 'baremes_indemnites',
                'ordering': ['zone', 'categorie_employe'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_mission', models.CharField(choices=[('mission_interne', 'Mission interne'), ('mission_externe', 'Mission externe'), ('formation', 'Formation'), ('conference', 'Conférence/Séminaire'), ('prospection', 'Prospection commerciale'), ('audit', 'Audit'), ('installation', 'Installation/Maintenance'), ('autre', 'Autre')], max_length=30)),
                ('objet', models.CharField(help_text='Objet de la mission', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('lieu_depart', models.CharField(default='Conakry', max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('pays', models.CharField(default='Guinée', max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_retour', models.TimeField(blank=True, null=True)),
                ('moyen_transport', models.CharField(choices=[('vehicule_service', 'Véhicule de service'), ('vehicule_personnel', 'Véhicule personnel'), ('avion', 'Avion'), ('train', 'Train'), ('bus', 'Bus'), ('taxi', 'Taxi'), ('autre', 'Autre')], default='vehicule_service', max_length=30)),
                ('details_transport', models.TextField(blank=True, help_text='Détails du transport')),
                ('avec_hebergement', models.BooleanField(default=False)),
                ('hotel', models.CharField(blank=True, max_length=200)),
                ('adresse_hebergement', models.TextField(blank=True)),
                ('budget_previsionnel', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('avance_accordee', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('depenses_reelles', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('indemnite_journaliere', models.DecimalField(decimal_places=2, default=0, help_text='Per diem journalier', max_digits=15)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('rapport_mission', models.TextField(blank=True, help_text='Compte-rendu de mission')),
                ('objectifs_atteints', models.BooleanField(default=False)),
                ('ordre_mission', models.FileField(blank=True, help_text='Ordre de mission signé', null=True, upload_to='missions/ordres/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='employes.employe')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_validees', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FraisMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('transport', 'Transport'), ('hebergement', 'Hébergement'), ('restauration', 'Restauration'), ('communication', 'Communication'), ('representation', 'Représentation'), ('divers', 'Divers')], max_length=30)),
                ('date_depense', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='missions/justificatifs/%Y/%m/')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='employes.mission')),
            ],
            options={
                'verbose_name': 'Frais de mission',
                'verbose_name_plural': 'Frais de mission',
                'db_table': 'frais_missions',
                'ordering': ['date_depense'],
            },
        ),
    ]
