# Generated by Django 5.2.7 on 2025-12-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0009_baremeindemnite_mission_fraismission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('delai_traitement_jours', models.IntegerField(default=5, help_text='Délai de traitement en jours ouvrables')),
                ('actif', models.BooleanField(default=True)),
                ('responsable_defaut', models.ForeignKey(blank=True, help_text='Responsable par défaut pour cette catégorie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_reclamations_responsable', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Catégorie de réclamation',
                'verbose_name_plural': 'Catégories de réclamations',
                'db_table': 'categories_reclamations',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('objet', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='reclamations/%Y/%m/')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours de traitement'), ('en_attente', "En attente d'information"), ('resolue', 'Résolue'), ('rejetee', 'Rejetée'), ('fermee', 'Fermée')], default='ouverte', max_length=20)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.TextField(blank=True, help_text='Réponse/résolution')),
                ('motif_rejet', models.TextField(blank=True)),
                ('satisfaction', models.IntegerField(blank=True, help_text='Note de satisfaction (1-5)', null=True)),
                ('commentaire_satisfaction', models.TextField(blank=True)),
                ('confidentiel', models.BooleanField(default=False, help_text='Réclamation confidentielle (visible uniquement par RH)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='employes.categoriereclamation')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='employes.employe')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'reclamations',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='reclamations/commentaires/%Y/%m/')),
                ('interne', models.BooleanField(default=False, help_text="Commentaire interne (non visible par l'employé)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='employes.reclamation')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'commentaires_reclamations',
                'ordering': ['date_creation'],
            },
        ),
    ]
