# Generated by Django 5.2.7 on 2025-12-28 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0010_categoriereclamation_reclamation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongeMaternite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accouchement_prevue', models.DateField()),
                ('date_accouchement_reelle', models.DateField(blank=True, null=True)),
                ('date_debut_prenatal', models.DateField(help_text='6 semaines avant accouchement')),
                ('date_fin_postnatal', models.DateField(help_text='8 semaines après accouchement')),
                ('prolongation_maladie', models.BooleanField(default=False)),
                ('date_fin_prolongation', models.DateField(blank=True, null=True)),
                ('certificat_medical_prolongation', models.FileField(blank=True, null=True, upload_to='maternite/certificats/')),
                ('conge_non_paye', models.BooleanField(default=False)),
                ('date_fin_conge_non_paye', models.DateField(blank=True, null=True)),
                ('indemnite_journaliere_cnss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_indemnites_cnss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('en_cours', 'En cours'), ('prolonge', 'Prolongé'), ('termine', 'Terminé'), ('refuse', 'Refusé')], default='demande', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges_maternite', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Congé maternité',
                'verbose_name_plural': 'Congés maternité',
                'db_table': 'conges_maternite',
                'ordering': ['-date_accouchement_prevue'],
            },
        ),
        migrations.CreateModel(
            name='EnfantEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('scolarise', models.BooleanField(default=False, help_text="Si scolarisé, éligible jusqu'à 20 ans")),
                ('certificat_scolarite', models.FileField(blank=True, null=True, upload_to='enfants/scolarite/')),
                ('acte_naissance', models.FileField(blank=True, null=True, upload_to='enfants/actes/')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Enfant employé',
                'verbose_name_plural': 'Enfants employés',
                'db_table': 'enfants_employes',
                'ordering': ['employe', '-date_naissance'],
            },
        ),
        migrations.CreateModel(
            name='FinContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('licenciement_economique', 'Licenciement économique'), ('licenciement_faute_simple', 'Licenciement pour faute simple'), ('licenciement_faute_grave', 'Licenciement pour faute grave'), ('licenciement_faute_lourde', 'Licenciement pour faute lourde'), ('licenciement_inaptitude', 'Licenciement pour inaptitude'), ('demission', 'Démission'), ('rupture_conventionnelle', 'Rupture conventionnelle'), ('fin_cdd', 'Fin de CDD'), ('fin_periode_essai', "Fin de période d'essai"), ('retraite', 'Départ à la retraite'), ('deces', 'Décès')], max_length=50)),
                ('date_notification', models.DateField(help_text='Date de notification de la fin de contrat')),
                ('date_debut_preavis', models.DateField(blank=True, null=True)),
                ('date_fin_preavis', models.DateField(blank=True, null=True)),
                ('duree_preavis_mois', models.IntegerField(default=0, help_text='Durée du préavis en mois')),
                ('preavis_dispense', models.BooleanField(default=False, help_text='Dispense de préavis')),
                ('indemnite_preavis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('anciennete_annees', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salaire_moyen_reference', models.DecimalField(decimal_places=2, default=0, help_text='Salaire moyen des 12 derniers mois', max_digits=15)),
                ('indemnite_licenciement', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('detail_calcul_indemnite', models.JSONField(blank=True, default=dict)),
                ('indemnite_conges_payes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('indemnite_compensatrice', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('autres_indemnites', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_indemnites', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lettre_licenciement', models.FileField(blank=True, null=True, upload_to='fins_contrat/lettres/')),
                ('certificat_travail', models.FileField(blank=True, null=True, upload_to='fins_contrat/certificats/')),
                ('solde_tout_compte', models.FileField(blank=True, null=True, upload_to='fins_contrat/soldes/')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('preavis', 'En préavis'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fins_contrat', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Fin de contrat',
                'verbose_name_plural': 'Fins de contrat',
                'db_table': 'fins_contrat',
                'ordering': ['-date_notification'],
            },
        ),
        migrations.CreateModel(
            name='PensionRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pension', models.CharField(choices=[('retraite_normale', 'Retraite normale'), ('retraite_anticipee', 'Retraite anticipée'), ('invalidite', 'Invalidité'), ('survivant', 'Pension de survivant')], max_length=30)),
                ('date_effet', models.DateField()),
                ('salaire_moyen_reference', models.DecimalField(decimal_places=2, default=0, help_text='Moyenne des 3-5 meilleures années', max_digits=15)),
                ('trimestres_cotises', models.IntegerField(default=0)),
                ('taux_pension', models.DecimalField(decimal_places=2, default=0, help_text='% du salaire de référence', max_digits=5)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notification_cnss', models.FileField(blank=True, null=True, upload_to='retraite/notifications/')),
                ('actif', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Pension de retraite',
                'verbose_name_plural': 'Pensions de retraite',
                'db_table': 'pensions_retraite',
                'ordering': ['-date_effet'],
            },
        ),
        migrations.CreateModel(
            name='AllocationFamiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.IntegerField()),
                ('nombre_enfants_eligibles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('montant_par_enfant', models.DecimalField(decimal_places=2, default=9000, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jours_travailles', models.IntegerField(default=0, help_text='Min 18 jours ou 120h/mois')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('eligible', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_familiales', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Allocation familiale',
                'verbose_name_plural': 'Allocations familiales',
                'db_table': 'allocations_familiales',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
