# Generated by Django 5.2.7 on 2026-01-04 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_demande_partenariat'),
        ('employes', '0012_alter_contratemploye_type_contrat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratemploye',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('CDImp', 'Contrat à Durée Imprécise'), ('CTI', 'Contrat de Travail Intermittent'), ('stage', 'Stage'), ('apprentissage', "Contrat d'Apprentissage"), ('temporaire', 'Temporaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('CDImp', 'Contrat à Durée Imprécise'), ('CTI', 'Contrat de Travail Intermittent'), ('stage', 'Stage'), ('apprentissage', "Contrat d'Apprentissage"), ('temporaire', 'Temporaire')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['entreprise', 'statut_employe'], name='idx_emp_entreprise_statut'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['entreprise', 'nom'], name='idx_emp_entreprise_nom'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['statut_employe'], name='idx_emp_statut'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['service'], name='idx_emp_service'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['type_contrat'], name='idx_emp_type_contrat'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['date_embauche'], name='idx_emp_date_embauche'),
        ),
    ]
