# Generated by Django 5.2.7 on 2026-01-04 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_demande_partenariat'),
        ('employes', '0013_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['matricule'], name='idx_emp_matricule'),
        ),
    ]
