# Generated by Django 5.2.7 on 2026-01-11 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0014_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfantemploye',
            name='etablissement_scolaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enfantemploye',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentemploye',
            name='type_document',
            field=models.CharField(choices=[('cv', 'CV'), ('diplome', 'Diplôme'), ('attestation', 'Attestation'), ('certificat', 'Certificat'), ('piece_identite', "Pièce d'identité"), ('acte_naissance', 'Acte de naissance'), ('acte_mariage', 'Acte de mariage'), ('livret_famille', 'Livret de famille'), ('certificat_medical', 'Certificat médical'), ('contrat', 'Contrat de travail'), ('avenant', 'Avenant au contrat'), ('attestation_travail', 'Attestation de travail'), ('lettre_recommandation', 'Lettre de recommandation'), ('certificat_emploi', "Certificat d'emploi antérieur"), ('fiche_paie', 'Fiche de paie'), ('photo', "Photo d'identité"), ('autre', 'Autre document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enfantemploye',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='ConjointEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employeur', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_mariage', models.DateField(blank=True, null=True)),
                ('lieu_mariage', models.CharField(blank=True, max_length=100, null=True)),
                ('acte_mariage', models.FileField(blank=True, null=True, upload_to='conjoints/actes_mariage/')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conjoint', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Conjoint employé',
                'verbose_name_plural': 'Conjoints employés',
                'db_table': 'conjoints_employes',
            },
        ),
    ]
