# Generated by Django 5.2.11 on 2026-03-24 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0015_add_conjoint_et_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='anciennete_transport_hcl',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancienneté transport HCL (ans)'),
        ),
        migrations.AddField(
            model_name='employe',
            name='base_chauffeur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chauffeur basé à'),
        ),
        migrations.AddField(
            model_name='employe',
            name='citerne',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Citerne assignée'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_dernier_recyclage',
            field=models.DateField(blank=True, null=True, verbose_name='Date dernier recyclage'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_derniere_visite_medicale',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière visite médicale'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_formation_apth',
            field=models.DateField(blank=True, null=True, verbose_name='Date formation APTH'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_obtention_permis',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention permis'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_prochaine_visite_medicale',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine visite médicale'),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_validite_permis',
            field=models.DateField(blank=True, null=True, verbose_name='Date validité permis'),
        ),
        migrations.AddField(
            model_name='employe',
            name='formation_extincteur',
            field=models.BooleanField(default=False, verbose_name='Formation extincteur'),
        ),
        migrations.AddField(
            model_name='employe',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='employe',
            name='id_conducteur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Conducteur'),
        ),
        migrations.AddField(
            model_name='employe',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='employe',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du père'),
        ),
        migrations.AddField(
            model_name='employe',
            name='nombre_femmes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de femmes'),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de permis'),
        ),
        migrations.AddField(
            model_name='employe',
            name='service_medical_accredite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Service médical accrédité'),
        ),
        migrations.AddField(
            model_name='employe',
            name='tracteur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracteur assigné'),
        ),
    ]
