# Generated by Django 5.2.11 on 2026-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0016_ajout_champs_conducteur_filiation_formation_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='vehicule_assigne',
            field=models.CharField(blank=True, help_text="Véhicule assigné à l'employé (immatriculation ou description)", max_length=200, null=True, verbose_name='Camion/Voiture assigné(e)'),
        ),
    ]
