# Generated by Django 5.2.7 on 2026-01-28 07:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('apprentissage', 'Apprentissage'), ('prestation', 'Prestation'), ('consultant', 'Consultant')], max_length=20)),
                ('duree_periode_essai_jours', models.IntegerField(default=90, help_text="Durée période d'essai en jours")),
                ('renouvelable', models.BooleanField(default=False)),
                ('duree_max_mois', models.IntegerField(blank=True, help_text='Durée maximale en mois (pour CDD)', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_contrats', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrats',
                'db_table': 'types_contrats',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrat', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_fin_periode_essai', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('heures_semaine', models.DecimalField(decimal_places=1, default=40.0, max_digits=4)),
                ('lieu_travail', models.CharField(blank=True, max_length=200, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré'), ('resilie', 'Résilié'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('date_fin_effective', models.DateField(blank=True, null=True)),
                ('motif_fin', models.CharField(blank=True, choices=[('demission', 'Démission'), ('licenciement', 'Licenciement'), ('fin_cdd', 'Fin de CDD'), ('retraite', 'Retraite'), ('deces', 'Décès'), ('abandon_poste', 'Abandon de poste'), ('fin_stage', 'Fin de stage'), ('rupture_conventionnelle', 'Rupture conventionnelle')], max_length=30, null=True)),
                ('commentaire_fin', models.TextField(blank=True, null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/documents/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to='employes.employe')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_gestion', to='employes.employe')),
                ('type_contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrats.typecontrat')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'contrats',
                'ordering': ['-date_debut'],
            },
        ),
    ]
