# Generated by Django 5.2.7 on 2026-01-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
        ('core', '0011_add_expatrie_fields'),
        ('employes', '0015_add_conjoint_et_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to='employes.employe'),
        ),
        migrations.AlterUniqueTogether(
            name='typecontrat',
            unique_together={('entreprise', 'nom')},
        ),
        migrations.CreateModel(
            name='AlerteContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('expiration', 'Expiration contrat'), ('fin_essai', "Fin période d'essai"), ('renouvellement', 'Renouvellement nécessaire'), ('document_manquant', 'Document manquant')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_alerte', models.DateField()),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('traitee', 'Traitée'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='contrats.contrat')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
            ],
            options={
                'verbose_name': 'Alerte contrat',
                'verbose_name_plural': 'Alertes contrats',
                'db_table': 'alertes_contrats',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='AvantageContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avantage', models.CharField(choices=[('transport', 'Transport'), ('logement', 'Logement'), ('telephone', 'Téléphone'), ('vehicule', 'Véhicule de fonction'), ('formation', 'Formation'), ('assurance', 'Assurance'), ('prime', 'Prime'), ('autre', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('valeur_mensuelle', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actif', models.BooleanField(default=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avantages', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Avantage contrat',
                'verbose_name_plural': 'Avantages contrats',
                'db_table': 'avantages_contrats',
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_disponibilite', models.CharField(choices=[('conge', 'Congé'), ('maladie', 'Maladie'), ('formation', 'Formation'), ('mission', 'Mission'), ('disponible', 'Disponible'), ('indisponible', 'Indisponible')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('approuve', models.BooleanField(default=False)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilites_approuvees', to='employes.employe')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Disponibilité employé',
                'verbose_name_plural': 'Disponibilités employés',
                'db_table': 'disponibilites_employes',
                'ordering': ['date_debut'],
            },
        ),
    ]
