# Generated by Django 5.2.6 on 2026-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_alter_contrat_cree_par_and_more'),
        ('employes', '0017_ajout_vehicule_assigne'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertecontrat',
            index=models.Index(fields=['contrat', 'statut'], name='idx_alerte_contrat_statut'),
        ),
        migrations.AddIndex(
            model_name='alertecontrat',
            index=models.Index(fields=['date_echeance'], name='idx_alerte_echeance'),
        ),
        migrations.AddIndex(
            model_name='avantagecontrat',
            index=models.Index(fields=['contrat', 'type_avantage'], name='idx_avantage_contrat_type'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['employe', 'statut'], name='idx_contrat_emp_statut'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['date_fin'], name='idx_contrat_date_fin'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['date_debut'], name='idx_contrat_date_debut'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['statut'], name='idx_contrat_statut'),
        ),
    ]
