# Generated by Django 5.2.7 on 2025-10-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_formation', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('type_formation', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe'), ('en_ligne', 'En ligne'), ('certifiante', 'Certifiante')], max_length=20)),
                ('domaine', models.CharField(choices=[('technique', 'Technique'), ('management', 'Management'), ('securite', 'Sécurité'), ('informatique', 'Informatique'), ('langues', 'Langues'), ('soft_skills', 'Soft Skills'), ('reglementaire', 'Réglementaire')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('duree_jours', models.IntegerField(help_text='Durée en jours')),
                ('duree_heures', models.IntegerField(help_text='Durée en heures')),
                ('prerequis', models.TextField(blank=True, null=True)),
                ('organisme_formateur', models.CharField(blank=True, max_length=200, null=True)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formation (Catalogue)',
                'verbose_name_plural': 'Catalogue des Formations',
                'db_table': 'catalogue_formations',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('note_contenu', models.IntegerField(help_text='Note sur 5')),
                ('note_formateur', models.IntegerField(help_text='Note sur 5')),
                ('note_organisation', models.IntegerField(help_text='Note sur 5')),
                ('note_moyens', models.IntegerField(help_text='Note sur 5')),
                ('note_globale', models.IntegerField(help_text='Note sur 5')),
                ('points_forts', models.TextField(blank=True, null=True)),
                ('points_ameliorer', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('competences_acquises', models.TextField(blank=True, null=True)),
                ('application_travail', models.BooleanField(default=True)),
                ('recommandation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Évaluation Formation',
                'verbose_name_plural': 'Évaluations Formation',
                'db_table': 'evaluations_formation',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('confirme', 'Confirmé'), ('present', 'Présent'), ('absent', 'Absent'), ('annule', 'Annulé')], default='inscrit', max_length=20)),
                ('note_evaluation', models.IntegerField(blank=True, help_text='Note sur 100', null=True)),
                ('appreciation', models.CharField(blank=True, max_length=50, null=True)),
                ('certificat_obtenu', models.BooleanField(default=False)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formation', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Inscription Formation',
                'verbose_name_plural': 'Inscriptions Formation',
                'db_table': 'inscriptions_formation',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='PlanFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget_consomme', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('en_cours', 'En cours'), ('cloture', 'Clôturé')], default='brouillon', max_length=20)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Formation',
                'verbose_name_plural': 'Plans de Formation',
                'db_table': 'plans_formation',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_session', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('formateur', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_places', models.IntegerField(default=10)),
                ('nombre_inscrits', models.IntegerField(default=0)),
                ('cout_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formation.catalogueformation')),
            ],
            options={
                'verbose_name': 'Session de Formation',
                'verbose_name_plural': 'Sessions de Formation',
                'db_table': 'sessions_formation',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.DeleteModel(
            name='FormationConfig',
        ),
        migrations.AddField(
            model_name='evaluationformation',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='formation.inscriptionformation'),
        ),
        migrations.AddField(
            model_name='inscriptionformation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formation.sessionformation'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionformation',
            unique_together={('session', 'employe')},
        ),
    ]
