# Generated by Django 5.2.7 on 2025-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('formation', '0002_catalogueformation_evaluationformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueformation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_formations', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='planformation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_formation', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='plan_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='formation.planformation'),
        ),
        migrations.AlterField(
            model_name='planformation',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='planformation',
            unique_together={('entreprise', 'annee')},
        ),
    ]
