# Generated by Django 5.2.7 on 2026-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_catalogueformation_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueformation',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogueformation',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de présentation de la formation', null=True, upload_to='formations/'),
        ),
        migrations.AddField(
            model_name='catalogueformation',
            name='publiee',
            field=models.BooleanField(default=False, help_text="Publier sur la page d'accueil publique"),
        ),
    ]
