# Generated by Django 5.2.7 on 2026-01-03 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_add_publication_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionFormationPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('contacte', 'Contacté'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('notes_admin', models.TextField(blank=True, help_text='Notes internes', null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_publiques', to='formation.catalogueformation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_publiques', to='formation.sessionformation')),
            ],
            options={
                'verbose_name': 'Inscription Formation (Public)',
                'verbose_name_plural': 'Inscriptions Formation (Public)',
                'db_table': 'inscriptions_formation_public',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
