# Generated by Django 5.2.7 on 2026-01-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_expatrie_fields'),
        ('formation', '0006_alter_catalogueformation_type_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueformation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_formations', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='planformation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_formation', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='plan_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='formation.planformation'),
        ),
        migrations.AlterField(
            model_name='catalogueformation',
            name='domaine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planformation',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='planformation',
            unique_together={('entreprise', 'annee')},
        ),
    ]
