# Generated by Django 4.2.7 on 2026-01-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formation", "0007_catalogueformation_entreprise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogueformation",
            name="domaine",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="catalogueformation",
            name="type_formation",
            field=models.CharField(max_length=500),
        ),
    ]
