# Generated by Django 5.2.6 on 2026-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0017_ajout_vehicule_assigne'),
        ('formation', '0008_alter_catalogueformation_domaine_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscriptionformation',
            index=models.Index(fields=['session', 'statut'], name='idx_inscription_sess_stat'),
        ),
        migrations.AddIndex(
            model_name='inscriptionformation',
            index=models.Index(fields=['employe'], name='idx_inscription_employe'),
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['formation', 'statut'], name='idx_session_form_statut'),
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['date_debut'], name='idx_session_date_debut'),
        ),
    ]
