# Generated by Django 5.2.7 on 2025-10-21 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code mémo de la constante', max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=15)),
                ('type_valeur', models.CharField(choices=[('montant', 'Montant'), ('pourcentage', 'Pourcentage'), ('nombre', 'Nombre')], max_length=20)),
                ('categorie', models.CharField(choices=[('cnss', 'CNSS'), ('irg', 'IRG'), ('inam', 'INAM'), ('general', 'Général'), ('temps', 'Temps de travail')], default='general', max_length=50)),
                ('unite', models.CharField(blank=True, help_text='%, GNF, jours, heures', max_length=20)),
                ('date_debut_validite', models.DateField()),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Constante',
                'verbose_name_plural': 'Constantes',
                'db_table': 'constantes',
                'ordering': ['categorie', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TrancheIRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tranche', models.IntegerField()),
                ('borne_inferieure', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borne_superieure', models.DecimalField(blank=True, decimal_places=2, help_text='Null = illimité', max_digits=15, null=True)),
                ('taux_irg', models.DecimalField(decimal_places=2, help_text='Taux en %', max_digits=5)),
                ('annee_validite', models.IntegerField()),
                ('date_debut_validite', models.DateField()),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tranche IRG',
                'verbose_name_plural': 'Tranches IRG',
                'db_table': 'tranches_irg',
                'ordering': ['annee_validite', 'numero_tranche'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code mémo de la variable', max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_variable', models.CharField(choices=[('numerique', 'Numérique'), ('texte', 'Texte'), ('booleen', 'Booléen'), ('date', 'Date')], max_length=20)),
                ('portee', models.CharField(choices=[('global', 'Global'), ('employe', 'Par employé'), ('periode', 'Par période')], max_length=20)),
                ('valeur_defaut', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'db_table': 'variables',
                'ordering': ['portee', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ParametrePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_en_cours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee_en_cours', models.IntegerField()),
                ('date_debut_periode', models.DateField()),
                ('date_fin_periode', models.DateField()),
                ('regulation_active', models.BooleanField(default=True, help_text='Activer la régulation automatique')),
                ('plafond_abattement_irg', models.DecimalField(decimal_places=2, default=300000, help_text='Plafond abattement IRG en GNF', max_digits=15)),
                ('taux_abattement_irg', models.DecimalField(decimal_places=2, default=20.0, help_text="Taux d'abattement IRG en %", max_digits=5)),
                ('type_bulletin_defaut', models.CharField(choices=[('standard', 'Standard'), ('simplifie', 'Simplifié'), ('detaille', 'Détaillé')], default='standard', max_length=20)),
                ('type_paiement_defaut', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('mobile_money', 'Mobile Money')], default='virement', max_length=20)),
                ('nombre_max_rubriques', models.IntegerField(default=100)),
                ('acompte_regulier_actif', models.BooleanField(default=True)),
                ('acompte_exceptionnel_actif', models.BooleanField(default=True)),
                ('montant_max_acompte_pct', models.DecimalField(decimal_places=2, default=50.0, help_text='% max du salaire', max_digits=5)),
                ('devise', models.CharField(default='GNF', max_length=3)),
                ('suppression_auto_non_presents', models.BooleanField(default=False, help_text='Supprimer les salariés non présents en clôture annuelle')),
                ('conserver_historique_admin', models.BooleanField(default=True)),
                ('duree_conservation_mois', models.IntegerField(default=120, help_text='Durée de conservation en mois')),
                ('nom_societe', models.CharField(blank=True, max_length=200)),
                ('adresse_societe', models.TextField(blank=True)),
                ('telephone_societe', models.CharField(blank=True, max_length=20)),
                ('email_societe', models.CharField(blank=True, max_length=100)),
                ('nif_societe', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50)),
                ('num_cnss_employeur', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre de paie',
                'verbose_name_plural': 'Paramètres de paie',
                'db_table': 'parametres_paie',
            },
        ),
    ]
