# Generated by Django 5.2.7 on 2025-12-17 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('employes', '0004_accidenttravail_avenantcontrat_equipementprotection_and_more'),
        ('paie', '0005_alter_periodepaie_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField()),
                ('date_accord', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nb_mensualites', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_restant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soldee', 'Soldée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('approuve_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_approuvees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_salaire', to='employes.employe')),
                ('periode_debut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_debut', to='paie.periodepaie')),
            ],
            options={
                'verbose_name': 'Avance sur salaire',
                'verbose_name_plural': 'Avances sur salaire',
                'db_table': 'avances_salaire',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declaration', models.CharField(choices=[('cnss_mensuelle', 'Déclaration CNSS mensuelle'), ('irpp_mensuelle', 'Déclaration IRPP mensuelle'), ('dipe', "DIPE - Déclaration Individuelle Préalable à l'Embauche"), ('etat_annuel', 'État récapitulatif annuel'), ('das', 'Déclaration Annuelle des Salaires')], max_length=30)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('effectif_declare', models.IntegerField(default=0)),
                ('masse_salariale', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('base_cotisation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('montant_cotisation_employe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_cotisation_employeur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('generee', 'Générée'), ('validee', 'Validée'), ('transmise', 'Transmise'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=20)),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_transmission', models.DateTimeField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('fichier_declaration', models.FileField(blank=True, null=True, upload_to='declarations/')),
                ('accuse_reception', models.FileField(blank=True, null=True, upload_to='declarations/ar/')),
                ('observations', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_sociales', to='core.entreprise')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_generees', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='paie.periodepaie')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration sociale',
                'verbose_name_plural': 'Déclarations sociales',
                'db_table': 'declarations_sociales',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='LigneDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_cotisation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cotisation_employe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cotisation_employeur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paie.bulletinpaie')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.declarationsociale')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employes.employe')),
            ],
            options={
                'verbose_name': 'Ligne de déclaration',
                'verbose_name_plural': 'Lignes de déclaration',
                'db_table': 'lignes_declarations',
            },
        ),
        migrations.CreateModel(
            name='SaisieArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_saisie', models.CharField(choices=[('pension_alimentaire', 'Pension alimentaire'), ('credit_bancaire', 'Crédit bancaire'), ('judiciaire', 'Saisie judiciaire'), ('fiscale', 'Saisie fiscale'), ('autre', 'Autre')], max_length=30)),
                ('reference_decision', models.CharField(help_text='Référence du jugement ou décision', max_length=100)),
                ('date_notification', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('taux_saisie', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage du salaire', max_digits=5, null=True)),
                ('quote_saisissable', models.DecimalField(decimal_places=2, default=33.33, help_text='Quote-part saisissable selon barème légal', max_digits=5)),
                ('beneficiaire', models.CharField(max_length=200)),
                ('rib_beneficiaire', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_preleve', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisies_arret', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Saisie-arrêt',
                'verbose_name_plural': 'Saisies-arrêt',
                'db_table': 'saisies_arret',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GrilleIndiciaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_grille', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('categorie', models.CharField(help_text='Catégorie professionnelle (A, B, C, D...)', max_length=20)),
                ('echelon', models.IntegerField(help_text='Échelon dans la catégorie')),
                ('indice', models.IntegerField(help_text='Indice de rémunération')),
                ('valeur_point', models.DecimalField(decimal_places=2, default=1, help_text='Valeur du point indiciaire', max_digits=10)),
                ('salaire_base', models.DecimalField(decimal_places=2, help_text='Salaire de base correspondant', max_digits=15)),
                ('convention_collective', models.CharField(blank=True, max_length=100, null=True)),
                ('date_effet', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grilles_indiciaires', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Grille indiciaire',
                'verbose_name_plural': 'Grilles indiciaires',
                'db_table': 'grilles_indiciaires',
                'ordering': ['categorie', 'echelon'],
                'unique_together': {('entreprise', 'categorie', 'echelon', 'date_effet')},
            },
        ),
    ]
