# Generated by Django 5.2.7 on 2025-12-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devise_configurationcnss_expatrie_permisvisa_and_more'),
        ('paie', '0006_avancesalaire_declarationsociale_lignedeclaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='devise_bulletin',
            field=models.ForeignKey(blank=True, help_text='Devise utilisée pour ce bulletin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_devise', to='core.devise'),
        ),
    ]
