# Generated by Django 5.2.7 on 2025-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0007_add_devise_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='token_public',
            field=models.CharField(blank=True, help_text='Token pour téléchargement public du PDF', max_length=64, null=True, unique=True),
        ),
    ]
