# Generated by Django 5.2.7 on 2025-12-28 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devise_configurationcnss_expatrie_permisvisa_and_more'),
        ('paie', '0008_add_token_public_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteEcheance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echeance', models.CharField(choices=[('cnss', 'Déclaration CNSS'), ('rts', 'Déclaration RTS'), ('vf', 'Versement Forfaitaire'), ('ta', "Taxe d'Apprentissage"), ('dmu', 'Déclaration Mensuelle Unique')], max_length=20)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('date_echeance', models.DateField(help_text='Date limite de déclaration (15 du mois suivant)')),
                ('date_alerte', models.DateField(help_text="Date à laquelle l'alerte a été créée")),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('urgent', 'Urgent'), ('en_retard', 'En retard'), ('traite', 'Traité')], default='a_venir', max_length=20)),
                ('niveau_alerte', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Urgent')], default='info', max_length=20)),
                ('jours_restants', models.IntegerField(default=0, help_text="Jours restants avant l'échéance")),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Montant estimé de la déclaration', max_digits=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='paie.declarationsociale')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_echeances', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Alerte échéance',
                'verbose_name_plural': 'Alertes échéances',
                'db_table': 'alertes_echeances',
                'ordering': ['date_echeance', '-niveau_alerte'],
                'unique_together': {('entreprise', 'type_echeance', 'annee', 'mois')},
            },
        ),
    ]
