# Generated by Django 5.2.7 on 2025-12-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0009_add_alerte_echeance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(help_text='Bulletin PDF archivé', upload_to='archives/bulletins/%Y/%m/')),
                ('taille_fichier', models.IntegerField(default=0, help_text='Taille en octets')),
                ('hash_fichier', models.CharField(blank=True, help_text='SHA256 pour vérification intégrité', max_length=64)),
                ('employe_matricule', models.CharField(max_length=20)),
                ('employe_nom', models.CharField(max_length=200)),
                ('periode_annee', models.IntegerField()),
                ('periode_mois', models.IntegerField()),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('nombre_telechargements', models.IntegerField(default=0)),
                ('dernier_telechargement', models.DateTimeField(blank=True, null=True)),
                ('bulletin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='paie.bulletinpaie')),
            ],
            options={
                'verbose_name': 'Archive bulletin',
                'verbose_name_plural': 'Archives bulletins',
                'db_table': 'archives_bulletins',
                'ordering': ['-periode_annee', '-periode_mois', 'employe_nom'],
                'indexes': [models.Index(fields=['employe_matricule', 'periode_annee', 'periode_mois'], name='archives_bu_employe_6921b9_idx'), models.Index(fields=['periode_annee', 'periode_mois'], name='archives_bu_periode_da91e4_idx')],
            },
        ),
    ]
