# Generated by Django 5.2.7 on 2025-12-28 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_add_apprentissage_contract_type'),
        ('paie', '0010_add_archive_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pret', models.CharField(help_text='Numéro unique du prêt', max_length=20, unique=True)),
                ('type_pret', models.CharField(choices=[('avance_salaire', 'Avance sur salaire'), ('pret_personnel', 'Prêt personnel'), ('pret_logement', 'Prêt logement'), ('pret_vehicule', 'Prêt véhicule'), ('pret_social', 'Prêt social'), ('autre', 'Autre')], default='avance_salaire', max_length=30)),
                ('montant_pret', models.DecimalField(decimal_places=2, help_text='Montant total du prêt', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, help_text="Taux d'intérêt annuel en %", max_digits=5)),
                ('montant_interets', models.DecimalField(decimal_places=2, default=0, help_text='Total des intérêts', max_digits=15)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, help_text='Montant total à rembourser', max_digits=15)),
                ('nombre_echeances', models.IntegerField(help_text='Nombre de mensualités', validators=[django.core.validators.MinValueValidator(1)])),
                ('montant_echeance', models.DecimalField(decimal_places=2, default=0, help_text='Montant de chaque échéance', max_digits=15)),
                ('date_debut_remboursement', models.DateField(help_text='Date de la première échéance')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, help_text='Montant déjà remboursé', max_digits=15)),
                ('solde_restant', models.DecimalField(decimal_places=2, default=0, help_text='Solde restant à rembourser', max_digits=15)),
                ('echeances_payees', models.IntegerField(default=0, help_text="Nombre d'échéances payées")),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'approbation"), ('approuve', 'Approuvé'), ('en_cours', 'En cours de remboursement'), ('solde', 'Soldé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True, help_text='Motif de la demande de prêt')),
                ('commentaire_approbation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approbateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_approuves', to='employes.employe')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'db_table': 'prets',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='EcheancePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.IntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_echeance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_avant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_apres', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_prets', to='paie.bulletinpaie')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='paie.pret')),
            ],
            options={
                'verbose_name': 'Échéance de prêt',
                'verbose_name_plural': 'Échéances de prêts',
                'db_table': 'echeances_prets',
                'ordering': ['pret', 'numero_echeance'],
                'unique_together': {('pret', 'numero_echeance')},
            },
        ),
    ]
