# Generated by Django 5.2.7 on 2025-12-28 10:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0008_evaluation_performance'),
        ('paie', '0011_add_pret_echeance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('plafond_journalier', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond journalier en GNF (optionnel)', max_digits=15, null=True)),
                ('justificatif_obligatoire', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de frais',
                'verbose_name_plural': 'Catégories de frais',
                'db_table': 'categories_frais',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='BaremeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employe', models.CharField(blank=True, choices=[('cadre_superieur', 'Cadre supérieur'), ('cadre', 'Cadre'), ('agent_maitrise', 'Agent de maîtrise'), ('employe', 'Employé'), ('ouvrier', 'Ouvrier')], help_text='Laisser vide pour tous', max_length=50)),
                ('plafond_unitaire', models.DecimalField(decimal_places=2, help_text='Plafond par dépense en GNF', max_digits=15)),
                ('plafond_journalier', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond par jour en GNF', max_digits=15, null=True)),
                ('plafond_mensuel', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond mensuel en GNF', max_digits=15, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremes', to='paie.categoriesfrais')),
            ],
            options={
                'verbose_name': 'Barème de frais',
                'verbose_name_plural': 'Barèmes de frais',
                'db_table': 'baremes_frais',
                'ordering': ['categorie', 'type_employe'],
            },
        ),
        migrations.CreateModel(
            name='NoteFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField(help_text='Début de la période')),
                ('date_fin', models.DateField(help_text='Fin de la période')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_valide', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('remboursee', 'Remboursée')], default='brouillon', max_length=20)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('date_remboursement', models.DateTimeField(blank=True, null=True)),
                ('mission', models.CharField(blank=True, help_text='Mission ou projet associé', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_frais', to='employes.employe')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_frais_validees', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Note de frais',
                'verbose_name_plural': 'Notes de frais',
                'db_table': 'notes_frais',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(default='GNF', max_length=3)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='frais/justificatifs/%Y/%m/')),
                ('numero_facture', models.CharField(blank=True, max_length=100)),
                ('valide', models.BooleanField(default=False)),
                ('montant_valide', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('motif_rejet', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_frais', to='paie.categoriesfrais')),
                ('note_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.notefrais')),
            ],
            options={
                'verbose_name': 'Ligne de frais',
                'verbose_name_plural': 'Lignes de frais',
                'db_table': 'lignes_frais',
                'ordering': ['date_depense'],
            },
        ),
    ]
