# Generated by Django 4.2.7 on 2026-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0012_categoriesfrais_baremefrais_notefrais_lignefrais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constante",
            name="code",
            field=models.CharField(
                help_text="Code mémo de la constante", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="code",
            field=models.CharField(
                help_text="Code mémo de la variable", max_length=50, unique=True
            ),
        ),
    ]
