# Generated by Django 5.2.7 on 2026-01-03 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_demande_partenariat'),
        ('paie', '0013_extend_constante_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrancheIRG',
            new_name='TrancheRTS',
        ),
        migrations.AlterModelOptions(
            name='trancherts',
            options={'ordering': ['annee_validite', 'numero_tranche'], 'verbose_name': 'Tranche RTS', 'verbose_name_plural': 'Tranches RTS'},
        ),
        migrations.AlterField(
            model_name='constante',
            name='categorie',
            field=models.CharField(choices=[('cnss', 'CNSS'), ('irg', 'RTS'), ('inam', 'INAM'), ('general', 'Général'), ('temps', 'Temps de travail')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='parametrepaie',
            name='plafond_abattement_irg',
            field=models.DecimalField(decimal_places=2, default=300000, help_text='Plafond abattement RTS en GNF', max_digits=15),
        ),
        migrations.AlterField(
            model_name='parametrepaie',
            name='taux_abattement_irg',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text="Taux d'abattement RTS en %", max_digits=5),
        ),
        migrations.CreateModel(
            name='ConfigurationPaieEntreprise',
            fields=[
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config_paie', serialize=False, to='core.entreprise')),
                ('mode_heures_sup', models.CharField(choices=[('code_travail', 'Code du Travail (+30%/+60%)'), ('convention', 'Convention Collective (+15%/+25%/+50%/+100%)'), ('personnalise', 'Personnalisé')], default='code_travail', max_length=20, verbose_name='Mode calcul HS')),
                ('taux_hs_4_premieres', models.DecimalField(decimal_places=2, default=30.0, help_text='Code du Travail: 30%, Convention: 15%', max_digits=5, verbose_name='Majoration 4 premières HS/semaine (%)')),
                ('taux_hs_au_dela', models.DecimalField(decimal_places=2, default=60.0, help_text='Code du Travail: 60%, Convention: 25%', max_digits=5, verbose_name='Majoration HS au-delà (%)')),
                ('taux_hs_nuit', models.DecimalField(decimal_places=2, default=50.0, help_text='20h-6h. Code du Travail: 20%, Convention: 50%', max_digits=5, verbose_name='Majoration heures de nuit (%)')),
                ('taux_hs_dimanche', models.DecimalField(decimal_places=2, default=100.0, help_text='Convention: 100%', max_digits=5, verbose_name='Majoration dimanche/férié jour (%)')),
                ('taux_hs_ferie_nuit', models.DecimalField(decimal_places=2, default=100.0, help_text='Convention: 100%', max_digits=5, verbose_name='Majoration férié nuit (%)')),
                ('mode_conges', models.CharField(choices=[('code_travail', 'Code du Travail (1,5 j/mois)'), ('convention', 'Convention Collective (2,5 j/mois)'), ('personnalise', 'Personnalisé')], default='code_travail', max_length=20, verbose_name='Mode calcul congés')),
                ('jours_conges_par_mois', models.DecimalField(decimal_places=2, default=1.5, help_text='Code du Travail: 1,5 j/mois (18j/an), Convention: 2,5 j/mois (30j/an)', max_digits=4, verbose_name='Jours de congé acquis par mois')),
                ('jours_conges_anciennete', models.DecimalField(decimal_places=2, default=2.0, help_text="Généralement +2 jours par 5 ans d'ancienneté", max_digits=4, verbose_name='Jours supplémentaires par tranche ancienneté')),
                ('tranche_anciennete_annees', models.IntegerField(default=5, help_text="Nombre d'années pour bonus congés", verbose_name='Tranche ancienneté (années)')),
                ('taux_cnss_employe', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux CNSS employé (%)')),
                ('taux_cnss_employeur', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux CNSS employeur (%)')),
                ('plafond_cnss', models.DecimalField(decimal_places=2, default=2500000.0, max_digits=15, verbose_name='Plafond CNSS (GNF)')),
                ('plancher_cnss', models.DecimalField(decimal_places=2, default=550000.0, max_digits=15, verbose_name='Plancher CNSS / SMIG (GNF)')),
                ('taux_versement_forfaitaire', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Versement Forfaitaire VF (%)')),
                ('taux_taxe_apprentissage', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name="Taxe d'Apprentissage TA (%)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration paie entreprise',
                'verbose_name_plural': 'Configurations paie entreprises',
                'db_table': 'config_paie_entreprise',
            },
        ),
    ]
