# Generated by Django 5.2.7 on 2026-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_demande_partenariat'),
        ('employes', '0013_performance_indexes'),
        ('paie', '0014_add_config_paie_entreprise'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bulletinpaie',
            index=models.Index(fields=['periode', 'statut_bulletin'], name='idx_bulletin_periode_statut'),
        ),
        migrations.AddIndex(
            model_name='bulletinpaie',
            index=models.Index(fields=['employe', 'annee_paie', 'mois_paie'], name='idx_bulletin_emp_periode'),
        ),
        migrations.AddIndex(
            model_name='bulletinpaie',
            index=models.Index(fields=['statut_bulletin'], name='idx_bulletin_statut'),
        ),
        migrations.AddIndex(
            model_name='bulletinpaie',
            index=models.Index(fields=['annee_paie', 'mois_paie'], name='idx_bulletin_annee_mois'),
        ),
        migrations.AddIndex(
            model_name='elementsalaire',
            index=models.Index(fields=['employe', 'actif'], name='idx_elem_employe_actif'),
        ),
        migrations.AddIndex(
            model_name='elementsalaire',
            index=models.Index(fields=['employe', 'date_debut', 'date_fin'], name='idx_elem_employe_dates'),
        ),
        migrations.AddIndex(
            model_name='elementsalaire',
            index=models.Index(fields=['rubrique'], name='idx_elem_rubrique'),
        ),
        migrations.AddIndex(
            model_name='lignebulletin',
            index=models.Index(fields=['bulletin'], name='idx_ligne_bulletin'),
        ),
        migrations.AddIndex(
            model_name='lignebulletin',
            index=models.Index(fields=['rubrique'], name='idx_ligne_rubrique'),
        ),
    ]
