# Generated by Django 5.2.7 on 2026-01-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0100_fix_taux_ta_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_normales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures normales travaillées', max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_supplementaires_30',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS à +30% (4 premières HS/semaine)', max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_supplementaires_60',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS à +60% (au-delà 4 HS/semaine)', max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_nuit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures de nuit (20h-6h) à +20%', max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='heures_feries',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures jours fériés', max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salaire de base', max_digits=15),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_heures_sup',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prime heures supplémentaires', max_digits=15),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_nuit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prime de nuit', max_digits=15),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_feries',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prime jours fériés', max_digits=15),
        ),
    ]
