# Generated by Django 5.2.6 on 2026-02-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0102_charges_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='contribution_onfpp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ONFPP 1,5% sur brut total', max_digits=15),
        ),
        migrations.AddField(
            model_name='configurationpaieentreprise',
            name='taux_onfpp',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Contribution ONFPP (%)'),
        ),
    ]
