# Generated by Django 5.2.6 on 2026-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0103_add_contribution_onfpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='rappel_salaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Complément salaire mois précédent (hors base)', max_digits=15),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='retenue_trop_percu',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retenue trop-perçu mois précédent (hors base)', max_digits=15),
        ),
    ]
