# Generated by Django 5.2.6 on 2026-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0104_add_rappel_salaire_retenue_trop_percu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpaie',
            name='taxe_apprentissage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TA 2% sur brut total', max_digits=15),
        ),
    ]
