# Generated by Django 5.2.6 on 2026-03-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0109_fix_taux_ta_et_soumis_irg'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='abattement_forfaitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abattement forfaitaire 25% sur base RTS', max_digits=15),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='base_vf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base de calcul du VF (brut - déduction)', max_digits=15),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='nombre_salaries',
            field=models.IntegerField(default=1, help_text='Nombre de salariés pour déterminer TA vs ONFPP'),
        ),
    ]
