# Generated by Django 5.2.6 on 2026-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0111_add_entreprise_rubriques_parametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='taux_ta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taux TA appliqué (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='taxe_apprentissage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TA 1,5% sur brut total', max_digits=15),
        ),
    ]
