# Generated by Django 5.2.6 on 2026-03-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0113_fix_taux_ta_2pourcent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpaie',
            name='taxe_apprentissage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TA 2% sur brut total', max_digits=15),
        ),
        migrations.AlterField(
            model_name='configurationpaieentreprise',
            name='taux_taxe_apprentissage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name="Taxe d'Apprentissage TA (%)"),
        ),
    ]
