# Generated by Django 5.2.6 on 2026-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0114_fix_models_taux_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriquepaie',
            name='categorie_rubrique',
            field=models.CharField(choices=[('salaire_base', 'Salaire de base'), ('prime', 'Prime (récompense/motivation)'), ('indemnite', 'Indemnité (compensation/remboursement)'), ('avantage', 'Avantage en nature'), ('cotisation', 'Cotisation sociale'), ('retenue', 'Retenue fiscale'), ('autre', 'Autre')], default='autre', help_text='Prime = imposable+CNSS | Indemnité = exonérable selon plafond', max_length=20),
        ),
        migrations.AddField(
            model_name='rubriquepaie',
            name='exonere_rts',
            field=models.BooleanField(default=False, help_text='Exonéré de RTS (indemnités forfaitaires, dans la limite du plafond 25%)'),
        ),
        migrations.AddField(
            model_name='rubriquepaie',
            name='inclus_brut',
            field=models.BooleanField(default=True, help_text='Inclus dans le salaire brut (False = versé en plus du net)'),
        ),
        migrations.AddField(
            model_name='rubriquepaie',
            name='mode_calcul',
            field=models.CharField(choices=[('fixe', 'Montant fixe'), ('pourcentage_base', '% du salaire de base'), ('pourcentage_brut', '% du brut'), ('horaire', 'Taux horaire × heures'), ('formule', 'Formule personnalisée')], default='fixe', help_text='Comment le montant est calculé', max_length=20),
        ),
    ]
