# Generated by Django 4.2.7 on 2026-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0118_historique_parametres_paie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletinpaie",
            name="heures_feries",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Heures jours fériés (jour)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpaie",
            name="prime_feries",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prime jours fériés (jour)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="historiqueparametrespaie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parametrescalculpaie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rubriquepaie",
            name="exonere_rts",
            field=models.BooleanField(
                default=False,
                help_text="Exonéré de RTS (indemnités forfaitaires intégralement exonérées, CGI Guinée)",
            ),
        ),
    ]
