# Generated by Django 5.2.6 on 2026-03-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0119_alter_bulletinpaie_heures_feries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trancherts',
            name='type_bareme',
            field=models.CharField(choices=[('officiel', 'Officiel (en vigueur)'), ('simulation', 'Simulation'), ('test', 'Test')], default='officiel', help_text='Officiel = utilisé pour les bulletins, Simulation/Test = comparaison uniquement', max_length=20),
        ),
    ]
