# Generated by Django 4.2.7 on 2026-03-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0120_snapshot_parametres_bulletin"),
        ("paie", "0122_simulation_fiscale"),
    ]

    operations = []
