# Generated by Django 5.2.6 on 2026-03-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0123_merge_20260328_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationfiscale',
            name='resultats_json',
            field=models.JSONField(default=list, help_text='Résultats comparatifs par barème (cnss, rts, net, détail tranches)'),
        ),
    ]
