# Generated by Django 4.2.29 on 2026-04-01 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entreprise_modules_quotas_plan'),
        ('employes', '0017_ajout_vehicule_assigne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paie', '0124_alter_simulationfiscale_resultats_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brut', models.DecimalField(decimal_places=0, max_digits=15)),
                ('composantes', models.JSONField(help_text='[{cle, label, pct, montant}, ...]')),
                ('impact', models.JSONField(help_text='{cnss, rts, net, taux_effectif, detail_tranches, regles, ...}')),
                ('comparaison', models.JSONField(blank=True, help_text='[{scenario, rts, cnss, net, taux}, ...]', null=True)),
                ('gain', models.JSONField(blank=True, help_text='{gain_net_mensuel, gain_net_annuel, ...}', null=True)),
                ('conformite', models.CharField(default='conforme', help_text='conforme / a_verifier / non_conforme', max_length=20)),
                ('avertissements', models.JSONField(blank=True, default=list, help_text='Liste des warnings détectés')),
                ('appliquee', models.BooleanField(default=False, help_text='True si les éléments ont été créés en lot')),
                ('date_application', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations_paie', to='employes.employe')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations_paie', to='core.entreprise')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation de paie',
                'verbose_name_plural': 'Simulations de paie',
                'db_table': 'simulations_paie',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['entreprise', '-date_creation'], name='idx_sim_entreprise_date'), models.Index(fields=['employe', '-date_creation'], name='idx_sim_employe_date')],
            },
        ),
    ]
