# Generated by Django 4.2.29 on 2026-04-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_entreprise_modules_quotas_plan'),
        ('paie', '0125_simulationpaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationpaie',
            name='version_bareme',
            field=models.CharField(default='GN-2026-v1', help_text='Version du barème fiscal utilisé', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validation', 'Validation simulation'), ('creation', 'Création éléments en lot'), ('pdf', 'Génération PDF')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Détails contextuels libres')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits_simulation', to='core.entreprise')),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='paie.simulationpaie')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit simulation',
                'verbose_name_plural': 'Audits simulation',
                'db_table': 'audit_simulations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entreprise', '-timestamp'], name='idx_audit_entreprise_ts')],
            },
        ),
    ]
