# Generated by Django 4.2.29 on 2026-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0126_simulationpaie_version_bareme_auditsimulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsimulation',
            name='action',
            field=models.CharField(choices=[('validation', 'Validation simulation'), ('creation', 'Création éléments en lot'), ('pdf', 'Génération PDF'), ('proposition', 'Proposition automatique complète')], max_length=20),
        ),
    ]
