# Generated by Django 4.2.7 on 2026-04-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0127_add_proposition_action_to_auditsimulation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrescalculpaie",
            name="mode_exoneration_indemnites",
            field=models.CharField(
                choices=[("plafond_pct", "Plafond % du brut (CGI strict)")],
                default="plafond_pct",
                max_length=20,
            ),
        ),
    ]
