# Generated by Django 5.2.1 on 2026-04-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_regle_indemnite_conformite'),
        ('paie', '0128_alter_parametrescalculpaie_mode_exoneration_indemnites'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleIndemnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_indemnite', models.CharField(choices=[('transport', 'Transport'), ('logement', 'Logement'), ('cherte_vie', 'Cherté de vie'), ('panier', 'Panier'), ('deplacement', 'Déplacement'), ('representation', 'Représentation'), ('autre', 'Autre')], max_length=30)),
                ('categorie_employe', models.CharField(choices=[('tous', 'Tous'), ('cadre', 'Cadre'), ('agent_maitrise', 'Agent de maîtrise'), ('employe', 'Employé'), ('ouvrier', 'Ouvrier')], default='tous', help_text='Catégorie professionnelle concernée (tous = toutes)', max_length=30)),
                ('seuil_min_pct', models.DecimalField(decimal_places=2, default=0, help_text='Seuil minimum recommandé (% du salaire de base)', max_digits=5)),
                ('seuil_max_pct', models.DecimalField(decimal_places=2, default=10, help_text='Seuil maximum recommandé (% du salaire de base)', max_digits=5)),
                ('justification_requise', models.CharField(blank=True, help_text='Justificatif attendu en cas de contrôle', max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_indemnites', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Règle indemnité',
                'verbose_name_plural': 'Règles indemnités',
                'db_table': 'regles_indemnites',
                'ordering': ['type_indemnite', 'categorie_employe'],
                'unique_together': {('entreprise', 'type_indemnite', 'categorie_employe')},
            },
        ),
        migrations.DeleteModel(
            name='SimulationFiscale',
        ),
    ]
