# Generated by Django 4.2.7 on 2026-04-25 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0018_licence_licencelocale"),
        ("paie", "0129_regle_indemnite_conformite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationFiscale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_simulation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "salaire_brut",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_indemnites",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
                (
                    "baremes_compares",
                    models.JSONField(
                        default=list, help_text="Labels lisibles des barèmes comparés"
                    ),
                ),
                (
                    "parametres_json",
                    models.JSONField(
                        default=dict, help_text="Snapshot barèmes + constantes utilisés"
                    ),
                ),
                (
                    "resultats_json",
                    models.JSONField(
                        default=list,
                        help_text="Résultats comparatifs par barème (cnss, rts, net, détail tranches)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations_fiscales",
                        to="core.entreprise",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations_fiscales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation fiscale",
                "verbose_name_plural": "Simulations fiscales",
                "db_table": "simulations_fiscales",
                "ordering": ["-date_simulation"],
                "indexes": [
                    models.Index(
                        fields=["entreprise", "date_simulation"],
                        name="idx_sim_entrep_date",
                    )
                ],
            },
        ),
    ]
