# Generated by Django 4.2.7 on 2026-04-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0130_add_arrondi_net"),
        ("paie", "0130_simulationfiscale"),
    ]

    operations = []
