# Generated by Django 5.2.7 on 2026-01-07 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_entreprise_type_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10)),
                ('est_courant', models.BooleanField(default=False, verbose_name='Exercice courant')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'db_table': 'exercices_comptables',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ecriture', models.CharField(max_length=20, verbose_name='N° Écriture')),
                ('date_ecriture', models.DateField(verbose_name='Date écriture')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('est_validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='core.entreprise')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.exercicecomptable')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'ecritures_comptables',
                'ordering': ['-date_ecriture', '-numero_ecriture'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, verbose_name='N° Facture')),
                ('type_facture', models.CharField(choices=[('achat', "Facture d'achat"), ('vente', 'Facture de vente')], max_length=10)),
                ('date_facture', models.DateField(verbose_name='Date facture')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='Date échéance')),
                ('reference_externe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. externe')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecriturecomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Code journal')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('type_journal', models.CharField(choices=[('AC', 'Achats'), ('VT', 'Ventes'), ('BQ', 'Banque'), ('CA', 'Caisse'), ('OD', 'Opérations diverses'), ('AN', 'À nouveau'), ('SA', 'Salaires')], max_length=2)),
                ('est_actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'journaux_comptables',
            },
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.journal'),
        ),
        migrations.CreateModel(
            name='PieceComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, verbose_name='N° Pièce')),
                ('type_piece', models.CharField(choices=[('FA', 'Facture achat'), ('FV', 'Facture vente'), ('RC', 'Reçu caisse'), ('RB', 'Relevé banque'), ('OD', 'Opération diverse')], max_length=2)),
                ('date_piece', models.DateField(verbose_name='Date pièce')),
                ('libelle', models.CharField(max_length=200)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='pieces_comptables/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_comptables', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Pièce comptable',
                'verbose_name_plural': 'Pièces comptables',
                'db_table': 'pieces_comptables',
                'ordering': ['-date_piece'],
            },
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='comptabilite.piececomptable'),
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, verbose_name='N° Compte')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('classe', models.CharField(choices=[('1', 'Classe 1 - Comptes de ressources durables'), ('2', "Classe 2 - Comptes d'actif immobilisé"), ('3', 'Classe 3 - Comptes de stocks'), ('4', 'Classe 4 - Comptes de tiers'), ('5', 'Classe 5 - Comptes de trésorerie'), ('6', 'Classe 6 - Comptes de charges'), ('7', 'Classe 7 - Comptes de produits'), ('8', 'Classe 8 - Comptes des autres charges'), ('9', 'Classe 9 - Comptes analytiques')], max_length=1)),
                ('est_actif', models.BooleanField(default=True)),
                ('solde_debiteur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solde_crediteur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_comptes', to='comptabilite.plancomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_comptables', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Plan comptable',
                'db_table': 'plan_comptable',
                'ordering': ['numero_compte'],
                'unique_together': {('entreprise', 'numero_compte')},
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.facture')),
                ('compte_comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.plancomptable')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de factures',
                'db_table': 'lignes_factures',
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('montant_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('montant_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecriturecomptable')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_ecritures', to='comptabilite.plancomptable')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écritures",
                'db_table': 'lignes_ecritures',
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='compte_contrepartie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.plancomptable'),
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, verbose_name='N° Règlement')),
                ('date_reglement', models.DateField(verbose_name='Date règlement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('mobile', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence paiement')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecriturecomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='core.entreprise')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='comptabilite.facture')),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'db_table': 'reglements',
                'ordering': ['-date_reglement'],
            },
        ),
        migrations.CreateModel(
            name='TauxTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('est_defaut', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('compte_tva_collectee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tva_collectee', to='comptabilite.plancomptable')),
                ('compte_tva_deductible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tva_deductible', to='comptabilite.plancomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_tva', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
                'db_table': 'taux_tva',
            },
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Code tiers')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('type_tiers', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('mixte', 'Client et Fournisseur')], max_length=15)),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('plafond_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.plancomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'db_table': 'tiers_comptables',
                'ordering': ['raison_sociale'],
                'unique_together': {('entreprise', 'code')},
            },
        ),
        migrations.AddField(
            model_name='piececomptable',
            name='tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.tiers'),
        ),
        migrations.AddField(
            model_name='facture',
            name='tiers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='comptabilite.tiers'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('entreprise', 'code')},
        ),
    ]
