# Generated by Django 5.2.7 on 2026-01-29 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_audit_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertenonconformite',
            new_name='comptabilit_entrepr_97b2ea_idx',
            old_name='comptabilite_a_entrap_sever_idx',
        ),
        migrations.RenameIndex(
            model_name='alertenonconformite',
            new_name='comptabilit_statut_9332e1_idx',
            old_name='comptabilite_a_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='alertenonconformite',
            new_name='comptabilit_date_co_28f15d_idx',
            old_name='comptabilite_a_date_c_idx',
        ),
        migrations.RenameIndex(
            model_name='declarationtva',
            new_name='comptabilit_entrepr_70af83_idx',
            old_name='comptabilite_declaration_tva_entreprise_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='declarationtva',
            new_name='comptabilit_periode_1a4a97_idx',
            old_name='comptabilite_declaration_tva_periode_debut_idx',
        ),
        migrations.RenameIndex(
            model_name='historiquemodification',
            new_name='comptabilit_entrepr_7fc486_idx',
            old_name='comptabilite_h_entrap_type_idx',
        ),
        migrations.RenameIndex(
            model_name='historiquemodification',
            new_name='comptabilit_utilisa_35c907_idx',
            old_name='comptabilite_h_util_date_idx',
        ),
        migrations.RenameIndex(
            model_name='historiquemodification',
            new_name='comptabilit_id_obje_b57d5c_idx',
            old_name='comptabilite_h_id_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='historiquemodification',
            new_name='comptabilit_date_mo_ce581c_idx',
            old_name='comptabilite_h_date_m_idx',
        ),
        migrations.RenameIndex(
            model_name='rapportaudit',
            new_name='comptabilit_entrepr_d59a8e_idx',
            old_name='comptabilite_r_entrap_idx1',
        ),
        migrations.RenameIndex(
            model_name='rapportaudit',
            new_name='comptabilit_date_de_76404d_idx',
            old_name='comptabilite_r_date_d_idx',
        ),
        migrations.RenameIndex(
            model_name='rapportaudit',
            new_name='comptabilit_code_ae1391_idx',
            old_name='comptabilite_r_code_idx',
        ),
        migrations.RenameIndex(
            model_name='regimetva',
            new_name='comptabilit_entrepr_33a311_idx',
            old_name='comptabilite_regime_tva_entreprise_actif_idx',
        ),
        migrations.RenameIndex(
            model_name='regimetva',
            new_name='comptabilit_code_bfb744_idx',
            old_name='comptabilite_regime_tva_code_idx',
        ),
        migrations.RenameIndex(
            model_name='reglesconformite',
            new_name='comptabilit_entrepr_3ef48d_idx',
            old_name='comptabilite_r_entrap_mod_idx',
        ),
        migrations.RenameIndex(
            model_name='reglesconformite',
            new_name='comptabilit_actif_1a52ec_idx',
            old_name='comptabilite_r_actif_idx',
        ),
        migrations.AddField(
            model_name='tauxtva',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tauxtva',
            name='utilisateur_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taux_tva_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tauxtva',
            name='utilisateur_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taux_tva_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
