# Generated by Django 5.2.7 on 2026-01-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0008_fiscalite_controle_analytique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationfiscale',
            name='declaration_irpp',
        ),
        migrations.DeleteModel(
            name='DeclarationIRPP',
        ),
    ]
