# Generated by Django 5.2.7 on 2026-01-31 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0010_contrats_archivage'),
        ('core', '0011_add_expatrie_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxTVASimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('est_defaut', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('compte_tva_collectee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tva_collectee', to='comptabilite.plancomptable')),
                ('compte_tva_deductible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tva_deductible', to='comptabilite.plancomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_tva_simple', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Taux de TVA (Simple)',
                'verbose_name_plural': 'Taux de TVA (Simple)',
                'db_table': 'taux_tva_simple',
            },
        ),
    ]
