# Generated by Django 4.2.29 on 2026-07-03 16:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_expatrie_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptabilite', '0011_tauxtvasimple'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numéro')),
                ('type_bordereau', models.CharField(choices=[('versement', 'Bordereau de versement (espèces)'), ('cheques', 'Bordereau de remise de chèques'), ('retrait', 'Bordereau de retrait')], max_length=10, verbose_name='Type')),
                ('date_remise', models.DateField(default=django.utils.timezone.now, verbose_name='Date de remise')),
                ('deposant', models.CharField(blank=True, max_length=200, verbose_name='Déposant')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptebancaire', verbose_name='Compte bancaire crédité')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux_remise', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Bordereau de remise',
                'verbose_name_plural': 'Bordereaux de remise',
                'db_table': 'bordereaux_remise',
                'ordering': ['-date_remise', '-id'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('achat', "Facture d'achat"), ('vente', 'Facture de vente'), ('avoir_client', "Facture d'avoir (client)"), ('avoir_fournisseur', "Facture d'avoir (fournisseur)"), ('acompte', "Facture d'acompte")], max_length=20),
        ),
        migrations.CreateModel(
            name='LigneBordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description / N° chèque')),
                ('banque_emettrice', models.CharField(blank=True, max_length=100, verbose_name='Banque émettrice')),
                ('tireur', models.CharField(blank=True, max_length=200, verbose_name='Tireur / Origine')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.bordereauremise')),
            ],
            options={
                'verbose_name': 'Ligne de bordereau',
                'verbose_name_plural': 'Lignes de bordereau',
                'db_table': 'lignes_bordereau',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name="Libellé de l'emprunt")),
                ('preteur', models.CharField(max_length=200, verbose_name='Prêteur / Banque')),
                ('reference_contrat', models.CharField(blank=True, max_length=100, verbose_name='Référence du contrat')),
                ('capital_emprunte', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Capital emprunté (GNF)')),
                ('taux_annuel', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Taux annuel (%)')),
                ('nombre_echeances', models.PositiveIntegerField(verbose_name="Nombre d'échéances")),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=15)),
                ('date_deblocage', models.DateField(verbose_name='Date de déblocage des fonds')),
                ('date_premiere_echeance', models.DateField(verbose_name='Date de la première échéance')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé'), ('contentieux', 'Contentieux')], default='en_cours', max_length=15)),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'db_table': 'emprunts',
                'ordering': ['-date_deblocage'],
            },
        ),
        migrations.CreateModel(
            name='PieceCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numéro de pièce')),
                ('type_piece', models.CharField(choices=[('entree', 'Entrée de caisse'), ('sortie', 'Sortie de caisse')], max_length=10, verbose_name='Type')),
                ('date_operation', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('libelle', models.CharField(max_length=255, verbose_name='Motif / Libellé')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire / Verseur (si tiers non référencé)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (facture, contrat…)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecriturecomptable', verbose_name='Écriture liée')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_caisse', to='core.entreprise')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.tiers', verbose_name='Tiers (payé à / reçu de)')),
            ],
            options={
                'verbose_name': 'Pièce de caisse',
                'verbose_name_plural': 'Pièces de caisse',
                'db_table': 'pieces_caisse',
                'ordering': ['-date_operation', '-id'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DeclarationPatente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name="Année d'imposition")),
                ('activite', models.CharField(max_length=255, verbose_name='Activité exercée')),
                ('reference_tarif', models.CharField(blank=True, max_length=100, verbose_name='Classe / référence du tarif des patentes')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name="Chiffre d'affaires (GNF)")),
                ('valeur_locative', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valeur locative des locaux (GNF)')),
                ('droit_fixe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Droit fixe (GNF)')),
                ('taux_proportionnel', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='Taux du droit proportionnel (%)')),
                ('droit_proportionnel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Droit proportionnel (GNF)')),
                ('date_declaration', models.DateField(default=django.utils.timezone.now, verbose_name='Date de déclaration')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('deposee', 'Déposée'), ('payee', 'Payée')], default='brouillon', max_length=10)),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_patente', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Déclaration de patente',
                'verbose_name_plural': 'Déclarations de patente',
                'db_table': 'declarations_patente',
                'ordering': ['-annee', '-date_declaration'],
                'unique_together': {('entreprise', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ChequeEmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=30, verbose_name='N° de chèque')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name='Bénéficiaire (ordre de)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('lieu_emission', models.CharField(default='Conakry', max_length=100, verbose_name="Lieu d'émission")),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif / Référence')),
                ('barre', models.BooleanField(default=True, verbose_name='Chèque barré (non endossable)')),
                ('statut', models.CharField(choices=[('emis', 'Émis'), ('encaisse', 'Encaissé'), ('annule', 'Annulé'), ('oppose', 'Opposition')], default='emis', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptebancaire', verbose_name='Compte bancaire tiré')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques_emis', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Chèque émis',
                'verbose_name_plural': 'Chèques émis',
                'db_table': 'cheques_emis',
                'ordering': ['-date_emission', '-id'],
                'unique_together': {('entreprise', 'compte_bancaire', 'numero_cheque')},
            },
        ),
        migrations.CreateModel(
            name='ArreteCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numéro')),
                ('date_arrete', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'arrêté")),
                ('nb_20000', models.PositiveIntegerField(default=0, verbose_name='Billets de 20 000')),
                ('nb_10000', models.PositiveIntegerField(default=0, verbose_name='Billets de 10 000')),
                ('nb_5000', models.PositiveIntegerField(default=0, verbose_name='Billets de 5 000')),
                ('nb_2000', models.PositiveIntegerField(default=0, verbose_name='Billets de 2 000')),
                ('nb_1000', models.PositiveIntegerField(default=0, verbose_name='Billets de 1 000')),
                ('nb_500', models.PositiveIntegerField(default=0, verbose_name='Billets de 500')),
                ('autres_valeurs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Autres valeurs (pièces, etc.)')),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Solde théorique (livre de caisse)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation / justification des écarts')),
                ('caissier', models.CharField(blank=True, max_length=200, verbose_name='Caissier')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arretes_caisse', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Arrêté de caisse',
                'verbose_name_plural': 'Arrêtés de caisse',
                'db_table': 'arretes_caisse',
                'ordering': ['-date_arrete', '-id'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
    ]
