# Generated by Django 5.2.6 on 2026-03-29 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_tauxtvasimple'),
        ('core', '0013_entreprise_modules_quotas_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['journal', 'date_ecriture'], name='idx_ecriture_journal_date'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['entreprise', 'date_ecriture'], name='idx_ecriture_ent_date'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['exercice'], name='idx_ecriture_exercice'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['tiers', 'date_facture'], name='idx_facture_tiers_date'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='idx_facture_statut'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_echeance'], name='idx_facture_echeance'),
        ),
    ]
