# Generated by Django 4.2.29 on 2026-07-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_bordereauremise_alter_facture_type_facture_and_more'),
        ('comptabilite', '0012_ecriturecomptable_idx_ecriture_journal_date_and_more'),
    ]

    operations = [
    ]
