# Generated by Django 4.2.29 on 2026-07-03 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0014_ecriturecomptable_piece_jointe_regleecriture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='centre_analyse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecritures', to='comptabilite.centreanalyse', verbose_name='Dimension analytique (projet, agence, centre de coût…)'),
        ),
    ]
