# Generated by Django 4.2.29 on 2026-07-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_accesentreprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptabilite', '0015_ligneecriture_centre_analyse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('facture', 'Facture'), ('reglement', 'Règlement / Paiement'), ('piece_caisse', 'Pièce de caisse'), ('operation', "Opération de l'assistant")], max_length=15)),
                ('seuil_montant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Seuil de déclenchement (GNF)')),
                ('nb_approbations', models.PositiveIntegerField(default=1, verbose_name="Nombre d'approbations requises")),
                ('niveau_acces_min', models.PositiveIntegerField(default=4, verbose_name="Niveau d'accès minimum de l'approbateur (1-5)")),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description (ex. : validation Directeur financier)')),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, help_text='Vide = règle globale (toutes les entreprises)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_validation', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Règle de validation',
                'verbose_name_plural': 'Règles de validation',
                'db_table': 'regles_validation',
                'ordering': ['type_document', 'seuil_montant'],
            },
        ),
        migrations.CreateModel(
            name='DemandeApprobation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('facture', 'Facture'), ('reglement', 'Règlement / Paiement'), ('piece_caisse', 'Pièce de caisse'), ('operation', "Opération de l'assistant")], max_length=15)),
                ('objet_id', models.CharField(max_length=100, verbose_name='Identifiant du document')),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approbation_emises', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_approbation', to='core.entreprise')),
                ('regle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.reglevalidation')),
            ],
            options={
                'verbose_name': "Demande d'approbation",
                'verbose_name_plural': "Demandes d'approbation",
                'db_table': 'demandes_approbation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DecisionApprobation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté')], max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('approbateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_approbation', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='comptabilite.demandeapprobation')),
            ],
            options={
                'verbose_name': "Décision d'approbation",
                'verbose_name_plural': "Décisions d'approbation",
                'db_table': 'decisions_approbation',
                'unique_together': {('demande', 'approbateur')},
            },
        ),
    ]
