# Generated by Django 5.2.7 on 2025-12-25 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_devise_configurationcnss_expatrie_permisvisa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=0, help_text='Prix en GNF', max_digits=12)),
                ('prix_annuel', models.DecimalField(decimal_places=0, help_text='Prix en GNF (avec réduction)', max_digits=12)),
                ('max_utilisateurs', models.IntegerField(default=5)),
                ('max_employes', models.IntegerField(default=50)),
                ('module_paie', models.BooleanField(default=True)),
                ('module_conges', models.BooleanField(default=True)),
                ('module_recrutement', models.BooleanField(default=False)),
                ('module_formation', models.BooleanField(default=False)),
                ('support_prioritaire', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'db_table': 'plans_abonnement',
                'ordering': ['ordre', 'prix_mensuel'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('token_paydunya', models.CharField(blank=True, max_length=255, null=True)),
                ('type_transaction', models.CharField(choices=[('abonnement', 'Abonnement'), ('renouvellement', 'Renouvellement'), ('upgrade', 'Mise à niveau')], default='abonnement', max_length=20)),
                ('methode_paiement', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('visa', 'Carte Visa'), ('mastercard', 'Carte Mastercard'), ('paydunya', 'PayDunya')], max_length=20, null=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('devise', models.CharField(default='GNF', max_length=3)),
                ('duree_mois', models.IntegerField(default=1, help_text="Durée de l'abonnement en mois")),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_expiration_abonnement', models.DateField(blank=True, null=True)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.entreprise')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.planabonnement')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('auto_renouvellement', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='core.entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.planabonnement')),
                ('derniere_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnement_actif', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'abonnements',
            },
        ),
    ]
