# Generated by Django 5.2.7 on 2025-10-21 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('date_jour_ferie', models.DateField()),
                ('annee', models.IntegerField()),
                ('type_ferie', models.CharField(choices=[('national', 'National'), ('religieux', 'Religieux'), ('local', 'Local')], max_length=50)),
                ('recurrent', models.BooleanField(default=False)),
                ('jour_recuperation', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'calendrier_jours_feries',
                'ordering': ['date_jour_ferie'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('type_absence', models.CharField(choices=[('maladie', 'Maladie'), ('accident_travail', 'Accident de travail'), ('absence_injustifiee', 'Absence injustifiée'), ('permission', 'Permission')], max_length=50)),
                ('duree_jours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('justifie', models.BooleanField(default=False)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='absences/')),
                ('impact_paie', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non payé'), ('partiellement_paye', 'Partiellement payé')], default='paye', max_length=20)),
                ('taux_maintien_salaire', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('observations', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'db_table': 'absences',
                'ordering': ['-date_absence'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('sans_solde', 'Congé sans solde')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('annee_reference', models.IntegerField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='conges/')),
                ('statut_demande', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('commentaire_approbateur', models.TextField(blank=True, null=True)),
                ('approbateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to='employes.employe')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employes.employe')),
                ('remplacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'db_table': 'conges',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pointage', models.DateField()),
                ('heure_entree', models.TimeField(blank=True, null=True)),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('heures_travaillees', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heures_supplementaires', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('statut_pointage', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('absence_justifiee', 'Absence justifiée')], default='present', max_length=20)),
                ('motif_absence', models.CharField(blank=True, max_length=50, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='pointages/')),
                ('valide', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'pointages',
                'ordering': ['-date_pointage'],
                'unique_together': {('employe', 'date_pointage')},
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('conges_acquis', models.DecimalField(decimal_places=2, default=26.0, max_digits=5)),
                ('conges_pris', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conges_restants', models.DecimalField(decimal_places=2, default=26.0, max_digits=5)),
                ('conges_reports', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_mise_a_jour', models.DateField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conges', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congés',
                'db_table': 'soldes_conges',
                'ordering': ['-annee'],
                'unique_together': {('employe', 'annee')},
            },
        ),
    ]
