# Generated by Django 5.2.7 on 2025-10-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        ('temps_travail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_horaire', models.CharField(max_length=20, unique=True)),
                ('libelle_horaire', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('heure_pause_debut', models.TimeField(blank=True, null=True)),
                ('heure_pause_fin', models.TimeField(blank=True, null=True)),
                ('heures_jour', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('type_horaire', models.CharField(choices=[('normal', 'Normal'), ('equipe', 'Équipe'), ('nuit', 'Nuit'), ('flexible', 'Flexible')], default='normal', max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horaire de travail',
                'verbose_name_plural': 'Horaires de travail',
                'db_table': 'horaires_travail',
                'ordering': ['code_horaire'],
            },
        ),
        migrations.CreateModel(
            name='ArretTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_arret', models.CharField(choices=[('maladie', 'Maladie'), ('accident_travail', 'Accident de travail'), ('maladie_professionnelle', 'Maladie professionnelle')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_jours', models.IntegerField(blank=True, null=True)),
                ('medecin_prescripteur', models.CharField(blank=True, max_length=100)),
                ('numero_certificat', models.CharField(blank=True, max_length=50)),
                ('organisme_payeur', models.CharField(choices=[('inam', 'INAM'), ('employeur', 'Employeur'), ('mixte', 'Mixte')], default='inam', max_length=50)),
                ('taux_indemnisation', models.DecimalField(decimal_places=2, default=100.0, help_text='% du salaire', max_digits=5)),
                ('montant_indemnites', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prolongation', models.BooleanField(default=False)),
                ('fichier_certificat', models.FileField(blank=True, null=True, upload_to='arrets_travail/')),
                ('observations', models.TextField(blank=True, null=True)),
                ('arret_initial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prolongations', to='temps_travail.arrettravail')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_travail', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Arrêt de travail',
                'verbose_name_plural': 'Arrêts de travail',
                'db_table': 'arrets_travail',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='AffectationHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_horaires', to='employes.employe')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='temps_travail.horairetravail')),
            ],
            options={
                'verbose_name': 'Affectation horaire',
                'verbose_name_plural': 'Affectations horaires',
                'db_table': 'affectation_horaires',
                'ordering': ['-date_debut'],
            },
        ),
    ]
