# Generated by Django 5.2.7 on 2025-12-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('temps_travail', '0002_horairetravail_arrettravail_affectationhoraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='horairetravail',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horaires_travail', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='jourferie',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='core.entreprise'),
        ),
    ]
