# Generated by Django 5.2.7 on 2025-12-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('employes', '0004_accidenttravail_avenantcontrat_equipementprotection_and_more'),
        ('temps_travail', '0003_horairetravail_entreprise_jourferie_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('annuel', 'Congé annuel (2,5j/mois)'), ('anciennete', "Congé d'ancienneté"), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité (14 semaines)'), ('paternite', 'Congé paternité (3 jours)'), ('mariage', 'Congé mariage (4 jours)'), ('naissance', 'Congé naissance (3 jours)'), ('deces_conjoint', 'Décès conjoint/enfant (5 jours)'), ('deces_parent', 'Décès parent/beau-parent (3 jours)'), ('deces_autre', 'Décès autre famille (1 jour)'), ('formation', 'Congé formation'), ('examen', 'Congé pour examen'), ('sans_solde', 'Congé sans solde'), ('recuperation', 'Récupération')], max_length=50),
        ),
        migrations.CreateModel(
            name='DroitConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('periode_reference_debut', models.DateField()),
                ('periode_reference_fin', models.DateField()),
                ('jours_acquis_base', models.DecimalField(decimal_places=2, default=0, help_text='Jours acquis (base 2,5j/mois)', max_digits=5)),
                ('jours_acquis_anciennete', models.DecimalField(decimal_places=2, default=0, help_text='Jours supplémentaires ancienneté', max_digits=5)),
                ('jours_reportes', models.DecimalField(decimal_places=2, default=0, help_text='Jours reportés année précédente', max_digits=5)),
                ('jours_exceptionnels', models.DecimalField(decimal_places=2, default=0, help_text='Jours exceptionnels accordés', max_digits=5)),
                ('jours_pris', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('jours_planifies', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('solde_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('indemnite_conge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits_conges', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Droit aux congés',
                'verbose_name_plural': 'Droits aux congés',
                'db_table': 'droits_conges',
                'unique_together': {('employe', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ReglementationTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('duree_hebdo_legale', models.DecimalField(decimal_places=2, default=40.0, help_text='Durée hebdomadaire légale (40h en Guinée)', max_digits=4)),
                ('duree_journaliere_max', models.DecimalField(decimal_places=2, default=10.0, help_text='Durée journalière maximale', max_digits=4)),
                ('taux_hs_jour_25', models.DecimalField(decimal_places=2, default=125.0, help_text='Taux HS jour (1-8h): 125%', max_digits=5)),
                ('taux_hs_jour_50', models.DecimalField(decimal_places=2, default=150.0, help_text='Taux HS jour (>8h): 150%', max_digits=5)),
                ('taux_hs_nuit', models.DecimalField(decimal_places=2, default=150.0, help_text='Taux HS nuit: 150%', max_digits=5)),
                ('taux_hs_dimanche', models.DecimalField(decimal_places=2, default=175.0, help_text='Taux HS dimanche/férié: 175%', max_digits=5)),
                ('taux_hs_nuit_dimanche', models.DecimalField(decimal_places=2, default=200.0, help_text='Taux HS nuit dimanche: 200%', max_digits=5)),
                ('heure_debut_nuit', models.TimeField(default='21:00', help_text='Début période de nuit')),
                ('heure_fin_nuit', models.TimeField(default='05:00', help_text='Fin période de nuit')),
                ('majoration_nuit', models.DecimalField(decimal_places=2, default=25.0, help_text='Majoration travail de nuit: 25%', max_digits=5)),
                ('repos_hebdo_jour', models.CharField(default='dimanche', help_text='Jour de repos hebdomadaire', max_length=20)),
                ('duree_repos_hebdo_min', models.IntegerField(default=24, help_text='Durée minimale repos hebdo (heures)')),
                ('jours_conges_annuels', models.DecimalField(decimal_places=2, default=26.0, help_text='Jours de congés annuels (2,5j/mois)', max_digits=4)),
                ('jours_conges_anciennete_5ans', models.IntegerField(default=1, help_text='Jours supplémentaires après 5 ans')),
                ('jours_conges_anciennete_10ans', models.IntegerField(default=2, help_text='Jours supplémentaires après 10 ans')),
                ('jours_conges_anciennete_15ans', models.IntegerField(default=3, help_text='Jours supplémentaires après 15 ans')),
                ('jours_conges_anciennete_20ans', models.IntegerField(default=4, help_text='Jours supplémentaires après 20 ans')),
                ('actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglementations_temps', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Réglementation temps de travail',
                'verbose_name_plural': 'Réglementations temps de travail',
                'db_table': 'reglementation_temps',
                'unique_together': {('entreprise', 'annee')},
            },
        ),
    ]
