# Generated by Django 5.2.7 on 2025-12-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_add_apprentissage_contract_type'),
        ('paie', '0010_add_archive_bulletin'),
        ('temps_travail', '0004_alter_conge_type_conge_droitconge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeureSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hs', models.DateField(help_text='Date des heures supplémentaires')),
                ('type_hs', models.CharField(choices=[('jour_15', 'Jour +15% (1-8h)'), ('jour_25', 'Jour +25% (1-8h)'), ('jour_50', 'Jour +50% (>8h)'), ('nuit_50', 'Nuit +50%'), ('dimanche_75', 'Dimanche/Férié +75%'), ('dimanche_nuit_100', 'Dimanche/Férié nuit +100%')], default='jour_25', max_length=20)),
                ('nombre_heures', models.DecimalField(decimal_places=2, help_text="Nombre d'heures", max_digits=5)),
                ('taux_majoration', models.DecimalField(decimal_places=2, help_text='Taux de majoration en %', max_digits=5)),
                ('taux_horaire_base', models.DecimalField(decimal_places=2, help_text='Taux horaire de base', max_digits=15)),
                ('montant_hs', models.DecimalField(decimal_places=2, help_text='Montant calculé', max_digits=15)),
                ('motif', models.TextField(blank=True, help_text='Motif des heures supplémentaires')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('paye', 'Payé')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heures_sup', to='paie.bulletinpaie')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures_supplementaires', to='employes.employe')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_validees', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Heure supplémentaire',
                'verbose_name_plural': 'Heures supplémentaires',
                'db_table': 'heures_supplementaires',
                'ordering': ['-date_hs', 'employe'],
            },
        ),
    ]
