# Generated by Django 5.2.7 on 2026-01-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0015_add_conjoint_et_docs'),
        ('temps_travail', '0005_add_heure_supplementaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_approuvees', to='employes.employe'),
        ),
        migrations.AddField(
            model_name='absence',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='heure_debut',
            field=models.TimeField(blank=True, help_text='Heure de début pour permissions partielles', null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='heure_fin',
            field=models.TimeField(blank=True, help_text='Heure de fin pour permissions partielles', null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='heures_a_recuperer',
            field=models.BooleanField(default=False, help_text='Heures à récupérer'),
        ),
        migrations.AddField(
            model_name='reglementationtemps',
            name='jours_conges_anciennete_25ans',
            field=models.IntegerField(default=10, help_text='Jours supplémentaires après 25 ans'),
        ),
        migrations.AddField(
            model_name='reglementationtemps',
            name='jours_conges_mineurs',
            field=models.DecimalField(decimal_places=2, default=24.0, help_text='Jours congés moins de 18 ans (2j/mois)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('maladie', 'Maladie'), ('accident_travail', 'Accident de travail'), ('absence_injustifiee', 'Absence injustifiée'), ('permission', 'Permission'), ('permission_exceptionnelle', 'Permission exceptionnelle'), ('rendez_vous_medical', 'Rendez-vous médical'), ('demarche_administrative', 'Démarche administrative'), ('urgence_familiale', 'Urgence familiale')], max_length=50),
        ),
        migrations.AlterField(
            model_name='droitconge',
            name='jours_acquis_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jours acquis (base 1,5j ouvrable/mois)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='heure_debut_nuit',
            field=models.TimeField(default='20:00', help_text='Début période de nuit (20h - Code du Travail)'),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='heure_fin_nuit',
            field=models.TimeField(default='06:00', help_text='Fin période de nuit (6h - Code du Travail)'),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='jours_conges_anciennete_10ans',
            field=models.IntegerField(default=4, help_text='Jours supplémentaires après 10 ans (+2j par tranche de 5 ans)'),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='jours_conges_anciennete_15ans',
            field=models.IntegerField(default=6, help_text='Jours supplémentaires après 15 ans'),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='jours_conges_anciennete_20ans',
            field=models.IntegerField(default=8, help_text='Jours supplémentaires après 20 ans'),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='jours_conges_anciennete_5ans',
            field=models.IntegerField(default=2, help_text='Jours supplémentaires après 5 ans (+2j)'),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='jours_conges_annuels',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Jours de congés annuels (1,5j ouvrable/mois)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='majoration_nuit',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Majoration travail de nuit: 20% (Art. 221)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='taux_hs_dimanche',
            field=models.DecimalField(decimal_places=2, default=160.0, help_text='Taux jour férié jour: 160% (majoration 60%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='taux_hs_jour_25',
            field=models.DecimalField(decimal_places=2, default=130.0, help_text='Taux 4 premières HS/semaine: 130% (majoration 30%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='taux_hs_jour_50',
            field=models.DecimalField(decimal_places=2, default=160.0, help_text='Taux au-delà 4 HS/semaine: 160% (majoration 60%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='taux_hs_nuit',
            field=models.DecimalField(decimal_places=2, default=120.0, help_text='Taux HS nuit (20h-6h): 120% (majoration 20%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reglementationtemps',
            name='taux_hs_nuit_dimanche',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Taux jour férié nuit: 200% (majoration 100%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='conges_acquis',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='conges_restants',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
