# Generated by Django 5.2.7 on 2026-01-29 07:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_expatrie_fields'),
        ('employes', '0015_add_conjoint_et_docs'),
        ('temps_travail', '0006_absence_approuve_par_absence_date_approbation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCongePublique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('formation', 'Congé formation'), ('sans_solde', 'Congé sans solde')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours_demandes', models.IntegerField()),
                ('motif', models.TextField()),
                ('document_justificatif', models.FileField(blank=True, help_text='Document signé ou justificatif médical', null=True, upload_to='conges/demandes_publiques/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('en_cours', 'En cours de traitement'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=20)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_traitement', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conges_publiques', to='employes.employe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_traites', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Demande de congé (publique)',
                'verbose_name_plural': 'Demandes de congés (publiques)',
                'db_table': 'demandes_conges_publiques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ParametrageConges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_conges_annuels', models.DecimalField(decimal_places=1, default=Decimal('18.0'), help_text='Nombre de jours de congés annuels de base', max_digits=4)),
                ('jours_par_mois', models.DecimalField(decimal_places=1, default=Decimal('1.5'), help_text='Nombre de jours acquis par mois travaillé', max_digits=3)),
                ('bonus_anciennete_actif', models.BooleanField(default=True)),
                ('jours_bonus_par_tranche', models.IntegerField(default=2)),
                ('annees_par_tranche', models.IntegerField(default=5)),
                ('jours_mineurs', models.IntegerField(default=24, help_text='Jours pour les moins de 18 ans')),
                ('report_autorise', models.BooleanField(default=True)),
                ('max_jours_report', models.IntegerField(default=5)),
                ('auto_calcul_actif', models.BooleanField(default=True)),
                ('mise_a_jour_mensuelle', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametrage_conges', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Paramétrage congés',
                'verbose_name_plural': 'Paramétrages congés',
                'db_table': 'parametrage_conges',
            },
        ),
        migrations.CreateModel(
            name='PermissionExceptionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_permission', models.CharField(choices=[('medicale', 'Rendez-vous médical'), ('administrative', 'Démarche administrative'), ('familiale', 'Événement familial'), ('urgence', 'Urgence personnelle'), ('formation', 'Formation externe'), ('autre', 'Autre motif')], max_length=20)),
                ('date_permission', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_heures', models.DecimalField(decimal_places=2, max_digits=4)),
                ('motif_detaille', models.TextField()),
                ('piece_justificative', models.FileField(help_text='Convocation, certificat médical, etc.', upload_to='permissions/justificatifs/')),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='demandee', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_approbation', models.TextField(blank=True, null=True)),
                ('deduction_salaire', models.BooleanField(default=False)),
                ('heures_a_recuperer', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_approuvees', to='employes.employe')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_exceptionnelles', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Permission exceptionnelle',
                'verbose_name_plural': 'Permissions exceptionnelles',
                'db_table': 'permissions_exceptionnelles',
                'ordering': ['-date_permission'],
            },
        ),
    ]
