# Generated by Django 5.2.7 on 2026-01-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "temps_travail",
            "0007_demandecongepublique_parametrageconges_and_more",
        ),
    ]

    operations = []
