# Generated by Django 5.2.6 on 2026-03-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_travail', '0007_demandecongepublique_parametrageconges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementationtemps',
            name='jours_conges_annuels',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Jours de congés annuels (2,5j ouvrable/mois = 30j/an, Code du Travail guinéen)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='conges_acquis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='conges_restants',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
