# Generated by Django 4.2.7 on 2026-03-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "temps_travail",
            "0008_alter_reglementationtemps_jours_conges_annuels_and_more",
        ),
        (
            "temps_travail",
            "0008_merge_20260131_1340",
        ),
    ]

    operations = []
