# Generated by Django 4.2.7 on 2026-03-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temps_travail", "0009_merge_20260308_0747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglementationtemps",
            name="jours_conges_annuels",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="Jours de congés annuels (1,5j ouvrable/mois)",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="soldeconge",
            name="conges_acquis",
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="soldeconge",
            name="conges_restants",
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
