# Generated by Django 4.2.7 on 2026-03-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "temps_travail",
            "0006_reglementationtemps_jours_conges_anciennete_25ans_and_more",
        ),
        (
            "temps_travail",
            "0010_alter_reglementationtemps_jours_conges_annuels_and_more",
        ),
    ]

    operations = []
