# Generated by Django 5.2.6 on 2026-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0017_ajout_vehicule_assigne'),
        ('temps_travail', '0011_merge_20260315_2017'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['employe', 'date_absence'], name='idx_absence_emp_date'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['date_absence'], name='idx_absence_date'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['employe', 'statut_demande'], name='idx_conge_emp_statut'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['date_debut', 'date_fin'], name='idx_conge_dates'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['statut_demande'], name='idx_conge_statut'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['employe', 'annee_reference'], name='idx_conge_emp_annee'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_pointage', 'statut_pointage'], name='idx_pointage_date_statut'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['employe', 'date_pointage'], name='idx_pointage_emp_date'),
        ),
    ]
