# Generated by Django 5.2.6 on 2026-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_travail', '0012_absence_idx_absence_emp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='statut_pointage',
            field=models.CharField(choices=[('present', 'Présent'), ('present_am', 'Présent AM'), ('present_pm', 'Présent PM'), ('present_am_pm', 'Présent AM et PM'), ('absent', 'Absent'), ('retard', 'Retard'), ('absence_justifiee', 'Absence justifiée'), ('malade', 'Malade'), ('p', 'P'), ('a', 'A')], default='present', max_length=20),
        ),
    ]
