# Generated by Django 5.2.7 on 2025-10-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cv', 'CV'), ('diplome', 'Diplôme'), ('attestation', 'Attestation'), ('certificat', 'Certificat'), ('piece_identite', "Pièce d'identité"), ('acte_naissance', 'Acte de naissance'), ('certificat_medical', 'Certificat médical'), ('contrat', 'Contrat de travail'), ('avenant', 'Avenant au contrat'), ('attestation_travail', 'Attestation de travail'), ('fiche_paie', 'Fiche de paie'), ('photo', "Photo d'identité"), ('autre', 'Autre document')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='documents_employes/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_document', models.DateField(blank=True, help_text='Date du document', null=True)),
                ('date_expiration', models.DateField(blank=True, help_text="Date d'expiration si applicable", null=True)),
                ('taille_fichier', models.IntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('confidentiel', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employes.employe')),
            ],
            options={
                'verbose_name': 'Document employé',
                'verbose_name_plural': 'Documents employés',
                'db_table': 'documents_employes',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
