# Generated by Django 5.2.7 on 2025-12-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devise_configurationcnss_expatrie_permisvisa_and_more'),
        ('employes', '0004_accidenttravail_avenantcontrat_equipementprotection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='devise_paie',
            field=models.ForeignKey(blank=True, help_text='Devise de paiement du salaire (par défaut GNF)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_devise', to='core.devise'),
        ),
    ]
