# Generated by Django 5.2.7 on 2025-12-17 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societe_entreprise'),
        ('dashboard', '0001_initial'),
        ('employes', '0003_employe_entreprise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardconfig',
            options={'verbose_name': 'Configuration dashboard'},
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='disposition',
            field=models.JSONField(default=dict, help_text='Disposition des widgets'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to='core.entreprise'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='widgets_actifs',
            field=models.JSONField(default=list, help_text='Liste des widgets activés'),
        ),
        migrations.AlterModelTable(
            name='dashboardconfig',
            table='dashboard_config',
        ),
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('bulletin_paie', 'Bulletin de paie'), ('contrat', 'Contrat de travail'), ('avenant', 'Avenant'), ('declaration', 'Déclaration sociale'), ('certificat', 'Certificat'), ('attestation', 'Attestation'), ('rapport', 'Rapport'), ('autre', 'Autre')], max_length=30)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='archives/')),
                ('taille_fichier', models.IntegerField(blank=True, null=True)),
                ('hash_fichier', models.CharField(blank=True, help_text='Hash SHA256 pour intégrité', max_length=64, null=True)),
                ('date_document', models.DateField()),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('duree_conservation_ans', models.IntegerField(default=10)),
                ('date_destruction_prevue', models.DateField(blank=True, null=True)),
                ('archive_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_archives', to='employes.employe')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Document archivé',
                'verbose_name_plural': 'Documents archivés',
                'db_table': 'archives_documents',
                'ordering': ['-date_archivage'],
            },
        ),
        migrations.CreateModel(
            name='RapportLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('registre_personnel', 'Registre du personnel'), ('etat_presence', 'État de présence mensuel'), ('bilan_social', 'Bilan social annuel'), ('rapport_formation', 'Rapport de formation'), ('rapport_accidents', 'Rapport accidents du travail'), ('rapport_inspection', 'Rapport inspection du travail'), ('das', 'Déclaration Annuelle des Salaires')], max_length=30)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('donnees', models.JSONField(default=dict, help_text='Données du rapport')),
                ('fichier_rapport', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('genere', 'Généré'), ('valide', 'Validé'), ('transmis', 'Transmis')], default='brouillon', max_length=20)),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_transmission', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_legaux', to='core.entreprise')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport légal',
                'verbose_name_plural': 'Rapports légaux',
                'db_table': 'rapports_legaux',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='TraceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('export', 'Export'), ('impression', 'Impression')], max_length=20)),
                ('module', models.CharField(help_text='Module concerné (employes, paie, etc.)', max_length=50)),
                ('table_concernee', models.CharField(max_length=50)),
                ('enregistrement_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces_audit', to='core.entreprise')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Trace d'audit",
                'verbose_name_plural': "Traces d'audit",
                'db_table': 'traces_audit',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='IndicateurRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_indicateur', models.CharField(choices=[('effectif', 'Effectif'), ('turnover', 'Turnover'), ('absenteisme', 'Absentéisme'), ('masse_salariale', 'Masse salariale'), ('formation', 'Formation'), ('recrutement', 'Recrutement'), ('heures_sup', 'Heures supplémentaires')], max_length=30)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valeur_precedente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('variation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('details', models.JSONField(default=dict, help_text='Détails du calcul')),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs_rh', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Indicateur RH',
                'verbose_name_plural': 'Indicateurs RH',
                'db_table': 'indicateurs_rh',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('entreprise', 'type_indicateur', 'annee', 'mois')},
            },
        ),
    ]
